import assert from "node:assert/strict";
import { generateKeyPairSync,randomUUID,sign } from "node:crypto";
import { existsSync,mkdtempSync,readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { LocalStore } from "../src/main/local-store";
import { OperationalLogger } from "../src/main/operational-log";
import type { Bootstrap,LeaseClaims } from "../src/shared/contracts";

const directory=mkdtempSync(path.join(tmpdir(),"abs-lab-lite-p3-")),dbPath=path.join(directory,"local.db"),backupPath=path.join(directory,"backup.db"),key="synthetic-test-key-"+randomUUID();
const pair=generateKeyPairSync("ed25519");
const issued=new Date(),claims:LeaseClaims={version:1,deviceId:"dev_syntheticdevice0001",tenantId:randomUUID(),branchId:randomUUID(),userId:randomUUID(),username:"offline",displayName:"Offline Counter",permissions:["billing:create","patients:create","refund:create","billing_adjustment:create"],authorizationVersion:"auth-v1",catalogVersion:"catalog-v1",issuedAt:issued.toISOString(),expiresAt:new Date(issued.getTime()+86400000).toISOString(),deviceEpoch:1};
const encoded=Buffer.from(JSON.stringify(claims)).toString("base64url"),leaseToken=`${encoded}.${sign(null,Buffer.from(encoded),pair.privateKey).toString("base64url")}`;
const patientId=randomUUID(),testId=randomUUID();
const bootstrap:Bootstrap={contractVersion:1,device:{id:claims.deviceId,tenantId:claims.tenantId,branchId:claims.branchId,epoch:1},tenant:{name:"Synthetic Offline Lab",currency_code:"BDT",timezone:"Asia/Dhaka",offline_max_bill_minor:"1000000",counter_discount_limit_bps:1000,admin_discount_limit_bps:5000},branch:{id:claims.branchId,code:"MAIN",name:"Main"},patients:[{id:patientId,patient_number:"P-001",full_name:"Synthetic Existing Patient",sex:"UNKNOWN",mobile:"01700000000",is_active:true,updated_at:issued.toISOString()}],doctors:[],partners:[],users:[],catalogVersion:claims.catalogVersion,catalog:[{id:testId,code:"OFF-1000",name:"Synthetic Offline Test",groupName:"Synthetic",priceMinor:100000,isActive:true}],leasePublicKeyPem:pair.publicKey.export({type:"spki",format:"pem"}).toString(),serverTime:issued.toISOString(),lease:{claims,token:leaseToken}};

let store=new LocalStore(dbPath,key);store.bootstrap(bootstrap,"Offline!Password123","installation-synthetic");const session=store.login("offline","Offline!Password123");assert.equal(session.userId,claims.userId);
store.saveDraft(session,"draft_operation_0001",{patientId,lines:[testId]});store.close();store=new LocalStore(dbPath,key);assert.equal(store.context().drafts.length,1,"draft survives process-store restart");
const operationId=`${claims.deviceId}_${randomUUID()}`;const bill=store.postBill(session,{operationId,newPatient:{id:randomUUID(),patientNumber:"OFF-P-002",fullName:"Synthetic New Offline Patient",mobile:"01800000000"},lines:[{testId,lineKey:"line-one",quantity:1}],payments:[{amount:"400",method:"CASH"}]});assert.equal(bill.netMinor,100000);assert.equal(bill.paidMinor,40000);assert.equal(bill.dueMinor,60000);assert.equal(store.state().pending,2,"patient and bill operations commit with the local ledger");assert.match(store.receiptHtml(bill.billId),new RegExp(bill.localReceiptNumber));
const billCountAfterPost=store.context().bills.length,firstReceipt=store.receiptHtml(bill.billId,"A5","PATIENT"),reprint=store.receiptHtml(bill.billId,"A5","DUPLICATE");assert.match(firstReceipt,new RegExp(bill.localReceiptNumber));assert.match(reprint,new RegExp(bill.localReceiptNumber));assert.throws(()=>store.receiptHtml("missing-bill"),/Bill not found/);assert.equal(store.context().bills.length,billCountAfterPost,"print generation failure and reprint never repost the bill");assert.equal((store.bill(bill.billId).bill as Record<string,unknown>).operation_id,operationId,"reprint keeps the original financial operation identity");
const before=store.context().bills.length;assert.throws(()=>store.postBill(session,{operationId:`${claims.deviceId}_${randomUUID()}`,patientId,lines:[{testId,lineKey:"reject",quantity:1}],payments:[{amount:"1001",method:"CASH"}]}),/exceeds/);assert.equal(store.context().bills.length,before,"failed local post rolls back completely");
const envelope=store.pendingEnvelopes().find(row=>row.operationId===operationId)!;store.applyAcks([{operationId,status:"ACKNOWLEDGED",outcome:{billId:"cloud-bill-1",billNumber:"MAIN-2026-000001",dueMinor:60000}}],new Date().toISOString());assert.equal((store.bill(bill.billId).bill as Record<string,unknown>).cloud_balance_minor,60000);store.applyPull([{status:"CLOUD_DUE_COLLECTION_CONFIRMED",billOperationId:operationId,outcome:{balanceMinor:0}}],1,new Date().toISOString());assert.equal((store.bill(bill.billId).bill as Record<string,unknown>).cloud_balance_minor,0);assert.equal((envelope.payload as Record<string,unknown>).localReceiptNumber,bill.localReceiptNumber);
const backup=store.backup(backupPath);assert.equal(backup.sha256.length,64);const restored=LocalStore.verifyBackup(backupPath,key,claims.deviceId);assert.equal(restored.deviceId,claims.deviceId);const restoredStore=new LocalStore(backupPath,key);const restoredBill=restoredStore.bill(bill.billId).bill as Record<string,unknown>;assert.equal(restoredBill.operation_id,operationId,"restore preserves financial operation identity");assert.equal(restoredBill.local_receipt_number,bill.localReceiptNumber,"restore preserves printed receipt identity");assert.equal(restoredStore.state().checkpoint,1,"restore preserves the synchronization checkpoint");restoredStore.close();store.close();
assert.throws(()=>{const wrong=new LocalStore(dbPath,"wrong-key");wrong.close();},/encrypted|database|malformed|file/i,"database is unreadable without its key");assert.notEqual(readFileSync(dbPath).subarray(0,16).toString(),"SQLite format 3\u0000","database header is encrypted");
const expiredClaims={...claims,issuedAt:new Date(Date.now()-7200000).toISOString(),expiresAt:new Date(Date.now()-3600000).toISOString()};const expiredEncoded=Buffer.from(JSON.stringify(expiredClaims)).toString("base64url"),expiredToken=`${expiredEncoded}.${sign(null,Buffer.from(expiredEncoded),pair.privateKey).toString("base64url")}`;const expiredDb=path.join(directory,"expired.db"),expired=new LocalStore(expiredDb,key);expired.bootstrap({...bootstrap,lease:{claims:expiredClaims,token:expiredToken}},"Offline!Password123","installation-synthetic");assert.throws(()=>expired.login("offline","Offline!Password123"),/expired/);expired.close();
const logDirectory=path.join(directory,"logs"),logger=new OperationalLogger(logDirectory,1,3);logger.write("sync_failure",{result:"failed",category:"network",password:"must-not-appear"} as Record<string,string>);logger.write("backup",{result:"success"});assert.ok(existsSync(path.join(logDirectory,"operations.jsonl.1")),"operational log rotates");const currentLog=readFileSync(path.join(logDirectory,"operations.jsonl"),"utf8");const rotatedLog=readFileSync(path.join(logDirectory,"operations.jsonl.1"),"utf8");assert.doesNotMatch(`${currentLog}${rotatedLog}`,/must-not-appear|password/,"unsafe fields are not written");
process.stdout.write(JSON.stringify({pass:true,localBill:{netMinor:100000,paidMinor:40000,dueMinor:60000},encryptedHeader:true,restartDraft:true,backupRestore:true})+"\n");
