export const BRANCH_ERROR_CODES = {
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  BRANCH_CODE_DUPLICATE: "BRANCH_CODE_DUPLICATE",
  BRANCH_INACTIVE: "BRANCH_INACTIVE",
  BRANCH_DEFAULT_REQUIRED: "BRANCH_DEFAULT_REQUIRED",
  BRANCH_DEFAULT_CANNOT_DEACTIVATE: "BRANCH_DEFAULT_CANNOT_DEACTIVATE",
  BRANCH_ACCESS_DENIED: "BRANCH_ACCESS_DENIED",
  BRANCH_ASSIGNMENT_INVALID: "BRANCH_ASSIGNMENT_INVALID",
  BRANCH_CROSS_TENANT: "BRANCH_CROSS_TENANT",
  BRANCH_USER_INACTIVE: "BRANCH_USER_INACTIVE",
  BRANCH_NO_AVAILABLE_BRANCH: "BRANCH_NO_AVAILABLE_BRANCH",
  BRANCH_VALIDATION: "BRANCH_VALIDATION",
  FORBIDDEN: "FORBIDDEN",
} as const;

export type BranchErrorCode = (typeof BRANCH_ERROR_CODES)[keyof typeof BRANCH_ERROR_CODES];

export function branchErrorMessage(code: BranchErrorCode, fallback: string): string {
  return fallback;
}
