import { requirePrincipal } from "../../../lib/session";
import { query } from "../../../lib/db";
import { createBranchAction, createUserAction, updateTenantAction } from "../../actions";
import { DeviceAdminPanel } from "../../../components/devices/DeviceAdminPanel";
import { listDevices } from "../../../services/devices";
export default async function SettingsPage() {
  const p = await requirePrincipal("tenant_settings", "read");
  const [tenant, branches, users, devices] = await Promise.all([
    query<{name:string;address:string|null;phone:string|null;email:string|null;receipt_footer:string|null;receipt_format:string;show_referral_partner_on_receipt:boolean;counter_discount_limit_bps:number;admin_discount_limit_bps:number}>(`select name,address,phone,email,receipt_footer,receipt_format,show_referral_partner_on_receipt,counter_discount_limit_bps,admin_discount_limit_bps from tenants where id=$1`,[p.tenantId]),
    query<{id:string;code:string;name:string}>(`select id,code,name from branches where tenant_id=$1 order by code`,[p.tenantId]),
    query<{id:string;username:string;display_name:string}>(`select id,username,display_name from users where tenant_id=$1 order by username`,[p.tenantId]),
    listDevices(p.tenantId),
  ]); const t=tenant.rows[0];
  return <main><h1>Tenant administration</h1><div className="grid"><section className="card"><h2>Branding and settings</h2><form className="stack" action={updateTenantAction}><label>Name<input name="name" defaultValue={t.name} required /></label><label>Address<textarea name="address" defaultValue={t.address??""} /></label><label>Phone<input name="phone" defaultValue={t.phone??""} /></label><label>Email<input name="email" defaultValue={t.email??""} /></label><label>Receipt footer<textarea name="receiptFooter" defaultValue={t.receipt_footer??""} /></label><label>Receipt format<select name="receiptFormat" defaultValue={t.receipt_format}><option>A4</option><option>A5</option><option value="POS80">POS 80mm</option><option value="POS58">POS 58mm</option></select></label><label><input type="checkbox" name="showReferral" defaultChecked={t.show_referral_partner_on_receipt}/> Show referral partner on patient receipts</label><label>Counter discount limit (basis points; 1000 = 10%)<input name="counterDiscountBps" type="number" min="0" max="10000" defaultValue={t.counter_discount_limit_bps}/></label><label>Administrator discount limit (basis points)<input name="adminDiscountBps" type="number" min="0" max="10000" defaultValue={t.admin_discount_limit_bps}/></label><button>Save settings</button></form></section>
  <section className="card"><h2>Branches</h2><form className="stack" action={createBranchAction}><label>Code<input name="code" required /></label><label>Name<input name="name" required /></label><label>Address<input name="address" /></label><label>Phone<input name="phone" /></label><button>Add branch</button></form><ul>{branches.rows.map(b=><li key={b.id}>{b.code} — {b.name}</li>)}</ul></section>
  <section className="card"><h2>Users and roles</h2><form className="stack" action={createUserAction}><label>Username<input name="username" required /></label><label>Display name<input name="displayName" required /></label><label>Temporary password<input name="password" type="password" required /></label><label>Role<select name="roleCode"><option>COUNTER</option><option>ACCOUNTS_VIEWER</option><option>LAB_ADMIN</option></select></label><label>Branch<select name="branchId">{branches.rows.map(b=><option key={b.id} value={b.id}>{b.code}</option>)}</select></label><button>Add user</button></form><ul>{users.rows.map(u=><li key={u.id}>{u.username} — {u.display_name}</li>)}</ul></section></div><DeviceAdminPanel branches={branches.rows} devices={devices as Parameters<typeof DeviceAdminPanel>[0]["devices"]}/></main>;
}
