import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { pool,query,verifyDatabaseIdentity } from "../src/lib/db";
import { provisionTenant,authenticate,resolveSession } from "../src/services/identity";
import { upsertGlobalTemplate,installTemplate } from "../src/services/catalog";
import { activateDevice,authenticateDevice,issueActivationCode,onlineDueCollection,setDeviceStatus,signLease,syncPull,syncPush,type SyncEnvelope } from "../src/services/devices";

test("Phase 3 device activation and synchronization",async t=>{
  await verifyDatabaseIdentity();assert.equal((await query<{name:string}>("select current_database() name")).rows[0].name,"abs_lab_lite_test");await query("truncate table tenants,catalog_templates cascade");
  await upsertGlobalTemplate({code:"P3-1000",name:"Synthetic Offline One Thousand",groupCode:"OFFLINE",specimenCode:"SYNTH",version:1,provenance:"PHASE3_TEST",reviewStatus:"UNREVIEWED",fields:[{code:"VALUE",name:"Synthetic Value",resultType:"NUMERIC"}]});
  const alpha=await provisionTenant({tenantCode:"P3ALPHA",tenantName:"Phase Three Alpha",branchCode:"MAIN",branchName:"Main",username:"admin",displayName:"Phase Three Admin",password:"Admin!PhaseThree123"});const beta=await provisionTenant({tenantCode:"P3BETA",tenantName:"Phase Three Beta",branchCode:"MAIN",branchName:"Main",username:"admin",displayName:"Other Tenant",password:"Beta!PhaseThree123"});await installTemplate(alpha.tenantId,"P3-1000","1000.00");
  const login=await authenticate({tenantCode:"P3ALPHA",branchCode:"MAIN",username:"admin",password:"Admin!PhaseThree123"});assert.ok(login);const principal=(await resolveSession(login.token))!;const activation=await issueActivationCode(principal,{branchId:alpha.branchId,expiresInMinutes:15});const deviceId="dev_phase3syntheticdevice0001",deviceSecret="synthetic-device-secret-with-sufficient-entropy",installationId="installation-phase3-0001";
  const bootstrap=await activateDevice({activationCode:activation.activationCode,deviceId,deviceSecret,installationId,deviceName:"Synthetic Counter",username:"admin",password:"Admin!PhaseThree123"});assert.equal(bootstrap.device.tenantId,alpha.tenantId);assert.equal(bootstrap.device.branchId,alpha.branchId);assert.ok(!JSON.stringify(bootstrap).includes("password_hash"));const context=await authenticateDevice(deviceId,deviceSecret,installationId);
  const testId=bootstrap.catalog[0].id,patientId=randomUUID(),patientOperation=`${deviceId}_${randomUUID()}`,billOperation=`${deviceId}_${randomUUID()}`,occurredAt=new Date().toISOString();
  const envelope=(operationId:string,operationType:SyncEnvelope["operationType"],payload:Record<string,unknown>,dependencies:string[]=[]):SyncEnvelope=>({contractVersion:1,operationId,operationType,tenantId:alpha.tenantId,branchId:alpha.branchId,deviceId,actorUserId:bootstrap.lease.claims.userId,occurredAtUtc:occurredAt,businessDate:occurredAt.slice(0,10),leaseToken:bootstrap.lease.token,dependencies,payload});
  const patient=envelope(patientOperation,"CREATE_PATIENT",{id:patientId,patientNumber:"OFF-P-001",fullName:"Synthetic Offline Patient",mobile:"01700000003",sex:"UNKNOWN"});const bill=envelope(billOperation,"POST_BILL",{patientId,localReceiptNumber:"MAIN-PHASE3-2026-000001",catalogVersion:bootstrap.catalogVersion,lines:[{testId,lineKey:"offline-line-1",quantity:1,unitPriceMinor:100000}],discountType:"NONE",discountValue:"0",payments:[{amount:"400",method:"CASH"}]},[patientOperation]);
  await t.test("offline upload reconciles one bill, 400 collection, and 600 receivable",async()=>{const first=await syncPush(context,[patient,bill]);assert.deepEqual(first.acknowledgements.map(x=>x.status),["ACKNOWLEDGED","ACKNOWLEDGED"]);const cloud=(await query<{id:string;net_minor:string}>(`select id,net_minor::text from bills where tenant_id=$1 and operation_id=$2`,[alpha.tenantId,billOperation])).rows[0];assert.equal(cloud.net_minor,"100000");assert.equal((await query<{sum:string}>(`select sum(amount_minor)::text sum from collections where tenant_id=$1 and bill_id=$2`,[alpha.tenantId,cloud.id])).rows[0].sum,"40000");});
  await t.test("lost acknowledgement retry is idempotent and conflicting reuse is rejected",async()=>{const replay=await syncPush(context,[bill]);assert.equal(replay.acknowledgements[0].status,"ACKNOWLEDGED");assert.equal(replay.acknowledgements[0].replayed,true);assert.equal((await query<{count:string}>(`select count(*)::text count from bills where tenant_id=$1 and operation_id=$2`,[alpha.tenantId,billOperation])).rows[0].count,"1");assert.equal((await query<{count:string}>(`select count(*)::text count from collections c join bills b on b.tenant_id=c.tenant_id and b.id=c.bill_id where b.tenant_id=$1 and b.operation_id=$2`,[alpha.tenantId,billOperation])).rows[0].count,"1");const changed={...bill,payload:{...bill.payload,discountType:"FIXED_AMOUNT",discountValue:"1"}};const conflict=await syncPush(context,[changed]);assert.equal(conflict.acknowledgements[0].status,"CONFLICTED");});
  await t.test("scope tampering and device credentials are rejected",async()=>{await assert.rejects(authenticateDevice(deviceId,"wrong",installationId),/Invalid device/);const tampered={...bill,operationId:`${deviceId}_${randomUUID()}`,tenantId:beta.tenantId};const result=await syncPush(context,[tampered]);assert.equal(result.acknowledgements[0].status,"QUARANTINED");assert.match(String(result.acknowledgements[0].error),/scope/);});
  await t.test("authorized catalog snapshot preserves the issued offline price",async()=>{await query(`update tenant_tests set price=2000 where tenant_id=$1 and id=$2`,[alpha.tenantId,testId]);const secondPatientId=randomUUID(),patientOp=`${deviceId}_${randomUUID()}`,billOp=`${deviceId}_${randomUUID()}`;const p=envelope(patientOp,"CREATE_PATIENT",{id:secondPatientId,patientNumber:"OFF-P-002",fullName:"Price Snapshot Patient",sex:"UNKNOWN"});const b=envelope(billOp,"POST_BILL",{patientId:secondPatientId,localReceiptNumber:"MAIN-PHASE3-2026-000002",catalogVersion:bootstrap.catalogVersion,lines:[{testId,lineKey:"offline-price-line",quantity:1,unitPriceMinor:100000}],payments:[]},[patientOp]);const result=await syncPush(context,[p,b]);assert.equal(result.acknowledgements[1].status,"ACKNOWLEDGED");assert.equal((await query<{unit_price_minor:string}>(`select bl.unit_price_minor::text from bill_lines bl join bills b on b.tenant_id=bl.tenant_id and b.id=bl.bill_id where b.tenant_id=$1 and b.operation_id=$2`,[alpha.tenantId,billOp])).rows[0].unit_price_minor,"100000");});
  await t.test("online-only due collection reaches exactly 1000 and pull refresh reaches zero",async()=>{const operationId=`${deviceId}_${randomUUID()}`;const due=await onlineDueCollection(context,{leaseToken:bootstrap.lease.token,billOperationId:billOperation,operationId,amount:"600",method:"CASH"});assert.equal((due.outcome as {balanceMinor:number}).balanceMinor,0);const sums=await query<{sum:string}>(`select sum(c.amount_minor)::text sum from collections c join bills b on b.tenant_id=c.tenant_id and b.id=c.bill_id where b.tenant_id=$1 and b.operation_id=$2`,[alpha.tenantId,billOperation]);assert.equal(sums.rows[0].sum,"100000");const pull=await syncPull(context,0);assert.ok(pull.events.some(event=>(event as Record<string,unknown>).status==="CLOUD_DUE_COLLECTION_CONFIRMED"));});
  await t.test("a legitimate pre-expiry queued operation can upload after lease expiry",async()=>{const claims={...bootstrap.lease.claims,issuedAt:new Date(Date.now()-7200000).toISOString(),expiresAt:new Date(Date.now()-3600000).toISOString()};const token=signLease(claims);const op=`${deviceId}_${randomUUID()}`;const queued={...envelope(op,"CREATE_PATIENT",{id:randomUUID(),patientNumber:"LATE-001",fullName:"Late Queued Patient",sex:"UNKNOWN"}),leaseToken:token,occurredAtUtc:new Date(Date.now()-5400000).toISOString()};const result=await syncPush(context,[queued]);assert.equal(result.acknowledgements[0].status,"ACKNOWLEDGED");});
  await t.test("revoked-device uploads are preserved and quarantined",async()=>{const queued=envelope(`${deviceId}_${randomUUID()}`,"CREATE_PATIENT",{id:randomUUID(),patientNumber:"REVOKED-001",fullName:"Revoked Evidence",sex:"UNKNOWN"});await setDeviceStatus(principal,deviceId,"REVOKED");const revoked=await authenticateDevice(deviceId,deviceSecret,installationId,false);const result=await syncPush(revoked,[queued]);assert.equal(result.acknowledgements[0].status,"QUARANTINED");assert.match(String(result.acknowledgements[0].error),/revoked/);assert.equal((await query<{count:string}>(`select count(*)::text count from device_sync_inbox where tenant_id=$1 and operation_id=$2`,[alpha.tenantId,queued.operationId])).rows[0].count,"1");});
  await pool.end();
});
