import assert from "node:assert/strict";
import test from "node:test";
import { pool,query,verifyDatabaseIdentity } from "../src/lib/db";
import { provisionTenant,createUser,authenticate,changeOwnPassword,resolveSession } from "../src/services/identity";
import { upsertGlobalTemplate,installTemplate } from "../src/services/catalog";
import { createPatient } from "../src/services/records";
import { cancelBill,cancelDraft,collectDue,dailyCollectionReport,decideRefund,getBillingRecord,payRefund,postBill,requestRefund,saveDraft,searchBillingContext } from "../src/services/billing";
import { POST as billingApi } from "../src/app/api/billing/route";

test("Phase 2 financial invariants",async(t)=>{
  await verifyDatabaseIdentity();assert.equal((await query<{name:string}>("select current_database() name")).rows[0].name,"abs_lab_lite_test");await query("truncate table tenants,catalog_templates cascade");
  await upsertGlobalTemplate({code:"P2-TEST",name:"Synthetic Phase Two Test",groupCode:"SYNTH",specimenCode:"SYNTH",version:1,provenance:"AUTOMATED_TEST",reviewStatus:"UNREVIEWED",fields:[{code:"VALUE",name:"Synthetic Value",resultType:"NUMERIC"}]});
  const alpha=await provisionTenant({tenantCode:"P2ALPHA",tenantName:"Phase Two Alpha",branchCode:"MAIN",branchName:"Main",username:"admin",displayName:"Admin Maker",password:"Admin!PhaseTwo123"});const beta=await provisionTenant({tenantCode:"P2BETA",tenantName:"Phase Two Beta",branchCode:"MAIN",branchName:"Main",username:"admin",displayName:"Beta Admin",password:"Beta!PhaseTwo123"});
  await installTemplate(alpha.tenantId,"P2-TEST","100.00");await installTemplate(beta.tenantId,"P2-TEST","900.00");const testId=(await query<{id:string}>(`select id from tenant_tests where tenant_id=$1 and code='P2-TEST'`,[alpha.tenantId])).rows[0].id;const betaTestId=(await query<{id:string}>(`select id from tenant_tests where tenant_id=$1 and code='P2-TEST'`,[beta.tenantId])).rows[0].id;const patient=(await createPatient({tenantId:alpha.tenantId,branchId:alpha.branchId,patientNumber:"P2-001",fullName:"Synthetic Billing Patient",mobile:"01700000000"}));
  const checker=await createUser({tenantId:alpha.tenantId,username:"checker",displayName:"Admin Checker",password:"Checker!PhaseTwo123",roleCode:"LAB_ADMIN",branchId:alpha.branchId});await changeOwnPassword(alpha.tenantId,checker.id,"Checker!PhaseTwo123","Checker!Changed456");
  const accounts=await createUser({tenantId:alpha.tenantId,username:"accounts",displayName:"Accounts Viewer",password:"Accounts!PhaseTwo123",roleCode:"ACCOUNTS_VIEWER",branchId:alpha.branchId});await changeOwnPassword(alpha.tenantId,accounts.id,"Accounts!PhaseTwo123","Accounts!Changed456");
  const adminLogin=await authenticate({tenantCode:"P2ALPHA",branchCode:"MAIN",username:"admin",password:"Admin!PhaseTwo123"});const checkerLogin=await authenticate({tenantCode:"P2ALPHA",branchCode:"MAIN",username:"checker",password:"Checker!Changed456"});const accountsLogin=await authenticate({tenantCode:"P2ALPHA",branchCode:"MAIN",username:"accounts",password:"Accounts!Changed456"});assert.ok(adminLogin&&checkerLogin&&accountsLogin);const admin=(await resolveSession(adminLogin.token))!;const checkerPrincipal=(await resolveSession(checkerLogin.token))!;
  const base=(operationId:string,payments:never[]|Array<{amount:string;method:"CASH"|"BKASH"}>=[])=>({operationId,patientId:patient.id,lines:[{testId,lineKey:`line_${operationId}`,quantity:1}],payments});

  await t.test("zero, partial, full, and split initial collections",async()=>{const zero=await postBill(admin,base("p2_zero_0001"));assert.equal(zero.dueMinor,10000);const partial=await postBill(admin,base("p2_partial_0001",[{amount:"40",method:"CASH"}]));assert.equal(partial.paidMinor,4000);assert.equal(partial.dueMinor,6000);const full=await postBill(admin,base("p2_full_0001",[{amount:"100",method:"CASH"}]));assert.equal(full.dueMinor,0);const split=await postBill(admin,base("p2_split_0001",[{amount:"30",method:"CASH"},{amount:"70",method:"BKASH"}]));assert.equal(split.paidMinor,10000);assert.equal((await query(`select 1 from collections where tenant_id=$1 and bill_id=$2`,[alpha.tenantId,split.billId])).rowCount,2);});

  await t.test("held bill can be resumed and cancelled without posting financial records",async()=>{const before=Number((await query<{count:string}>(`select count(*)::text count from bills where tenant_id=$1`,[alpha.tenantId])).rows[0].count);const held=await saveDraft(admin,{operationId:"p2_held_bill_0001",patientId:patient.id,payload:{patientId:patient.id,cart:[{testId,lineKey:"held-line",quantity:1}],printFormat:"POS80"}});const context=await searchBillingContext(alpha.tenantId);const draft=context.drafts.find(row=>row.id===held.id);assert.equal(String(draft?.operation_id),"p2_held_bill_0001");assert.equal((draft?.payload as Record<string,unknown>).printFormat,"POS80");assert.equal(Number((await query<{count:string}>(`select count(*)::text count from bills where tenant_id=$1`,[alpha.tenantId])).rows[0].count),before);await cancelDraft(admin,held.id);assert.equal((await searchBillingContext(alpha.tenantId)).drafts.some(row=>row.id===held.id),false);});

  await t.test("atomic rejection and idempotency payload consistency",async()=>{const before=Number((await query<{count:string}>(`select count(*)::text count from bills where tenant_id=$1`,[alpha.tenantId])).rows[0].count);await assert.rejects(postBill(admin,base("p2_atomic_0001",[{amount:"101",method:"CASH"}])),/exceeds/);assert.equal(Number((await query<{count:string}>(`select count(*)::text count from bills where tenant_id=$1`,[alpha.tenantId])).rows[0].count),before);const first=await postBill(admin,base("p2_idempotent_0001"));const replay=await postBill(admin,base("p2_idempotent_0001"));assert.equal(replay.billId,first.billId);assert.equal(replay.idempotent,true);await assert.rejects(postBill(admin,{...base("p2_idempotent_0001"),discountType:"FIXED_AMOUNT",discountValue:"1"}),/different content/);});

  await t.test("concurrent due collection cannot overcollect",async()=>{const bill=await postBill(admin,base("p2_concurrency_0001"));const results=await Promise.allSettled([collectDue(admin,{operationId:"p2_collect_a_0001",billId:String(bill.billId),amount:"80",method:"CASH"}),collectDue(admin,{operationId:"p2_collect_b_0001",billId:String(bill.billId),amount:"80",method:"BKASH"})]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal(results.filter(x=>x.status==="rejected").length,1);assert.equal((await query<{sum:string}>(`select sum(amount_minor)::text sum from collections where tenant_id=$1 and bill_id=$2`,[alpha.tenantId,bill.billId])).rows[0].sum,"8000");});

  await t.test("collection racing cancellation remains reconciled",async()=>{const bill=await postBill(admin,base("p2_race_0001"));const line=(await query<{id:string}>(`select id from bill_lines where tenant_id=$1 and bill_id=$2`,[alpha.tenantId,bill.billId])).rows[0];await Promise.allSettled([collectDue(admin,{operationId:"p2_race_collect_0001",billId:String(bill.billId),amount:"60",method:"CASH"}),cancelBill(admin,{operationId:"p2_race_cancel_0001",billId:String(bill.billId),lineIds:[line.id],reason:"Race invariant test"})]);const values=(await query<{adjusted:string;collected:string}>(`select coalesce((select sum(amount_minor) from bill_adjustments where tenant_id=$1 and bill_id=$2),0)::text adjusted,coalesce((select sum(amount_minor) from collections where tenant_id=$1 and bill_id=$2),0)::text collected`,[alpha.tenantId,bill.billId])).rows[0];assert.ok(Number(values.adjusted)<=10000);assert.ok(Number(values.collected)<=10000-Number(values.adjusted)||Number(values.adjusted)===10000);});

  await t.test("partial and whole cancellation preserve discount allocation",async()=>{const bill=await postBill(admin,{operationId:"p2_rounding_0001",patientId:patient.id,lines:[{testId,lineKey:"round_a",quantity:1},{testId,lineKey:"round_b",quantity:1,repeatReason:"Synthetic repeat"}],discountType:"FIXED_AMOUNT",discountValue:"0.01"});const lines=(await query<{id:string;line_key:string;discount_minor:string;net_minor:string}>(`select id,line_key,discount_minor::text,net_minor::text from bill_lines where tenant_id=$1 and bill_id=$2 order by line_key`,[alpha.tenantId,bill.billId])).rows;assert.deepEqual(lines.map(x=>Number(x.discount_minor)),[0,1]);const partial=await cancelBill(admin,{operationId:"p2_round_cancel_a",billId:String(bill.billId),lineIds:[lines[0].id],reason:"Partial cancellation"});assert.equal(partial.cancelledMinor,10000);const whole=await cancelBill(admin,{operationId:"p2_round_cancel_b",billId:String(bill.billId),reason:"Cancel remaining"});assert.equal(whole.cancelledMinor,9999);await assert.rejects(cancelBill(admin,{operationId:"p2_round_cancel_c",billId:String(bill.billId),reason:"Repeat cancellation"}),/already fully cancelled/);});

  await t.test("refund request, checker approval, payout, and duplicate protection",async()=>{const bill=await postBill(admin,base("p2_refund_bill_0001",[{amount:"100",method:"CASH"}]));await cancelBill(admin,{operationId:"p2_refund_cancel_0001",billId:String(bill.billId),reason:"Service cancelled"});const requested=await requestRefund(admin,{operationId:"p2_refund_request_0001",billId:String(bill.billId),amount:"50",reason:"Patient payout"});await assert.rejects(decideRefund(admin,{operationId:"p2_refund_self_decision",refundId:String(requested.refundId),approve:true}),/cannot approve/);const approved=await decideRefund(checkerPrincipal,{operationId:"p2_refund_decide_0001",refundId:String(requested.refundId),approve:true,reason:"Checked"});assert.equal(approved.status,"APPROVED");assert.equal((await query<{count:string}>(`select count(*)::text count from refunds where tenant_id=$1 and status='PAID'`,[alpha.tenantId])).rows[0].count,"0");const paid=await payRefund(checkerPrincipal,{operationId:"p2_refund_pay_0001",refundId:String(requested.refundId),method:"CASH",reference:"SYNTH-PAYOUT-1"});assert.equal(paid.status,"PAID");const replay=await payRefund(checkerPrincipal,{operationId:"p2_refund_pay_0001",refundId:String(requested.refundId),method:"CASH",reference:"SYNTH-PAYOUT-1"});assert.equal(replay.idempotent,true);await assert.rejects(requestRefund(admin,{operationId:"p2_refund_excess_0001",billId:String(bill.billId),amount:"51",reason:"Too much"}),/exceeds/);});

  await t.test("direct API permission and cross-tenant controls",async()=>{const denied=await billingApi(new Request("http://test/api/billing",{method:"POST",headers:{authorization:`Bearer ${accountsLogin.token}`,"content-type":"application/json"},body:JSON.stringify({action:"postBill",input:base("p2_api_denied_0001")})}));assert.equal(denied.status,403);await assert.rejects(postBill(admin,{operationId:"p2_cross_tenant_0001",patientId:patient.id,lines:[{testId:betaTestId,lineKey:"cross",quantity:1}]}),/invalid|belong/);});

  await t.test("business-day report reconciles and uses half-open boundaries",async()=>{const date=(await query<{date:string}>(`select (now() at time zone timezone)::date::text date from tenants where id=$1`,[alpha.tenantId])).rows[0].date;const report=await dailyCollectionReport(alpha.tenantId,{date});assert.equal(report.totals.netCollectionMinor,report.totals.initialCollectionsMinor+report.totals.oldDueCollectionsMinor-report.totals.paidRefundsMinor);assert.ok(report.startAt<report.endAt);const one=(await query<{id:string}>(`select id from collections where tenant_id=$1 order by collected_at limit 1`,[alpha.tenantId])).rows[0];await query(`update collections set collected_at=$2::timestamptz where tenant_id=$1 and id=$3`,[alpha.tenantId,report.endAt,one.id]);const excluded=await dailyCollectionReport(alpha.tenantId,{date});assert.equal(excluded.collections.some(x=>x.id===one.id),false);});

  await t.test("historical receipt snapshots survive master-data edits",async()=>{const bill=await postBill(admin,base("p2_snapshot_0001"));await query(`update patients set full_name='Changed Later' where tenant_id=$1 and id=$2`,[alpha.tenantId,patient.id]);await query(`update tenant_tests set name='Changed Catalog Later',price=999 where tenant_id=$1 and id=$2`,[alpha.tenantId,testId]);const receipt=await getBillingRecord(alpha.tenantId,"bill",String(bill.billId));assert.equal(String((receipt.bill as Record<string,unknown>).patient_name_snapshot),"Synthetic Billing Patient");assert.equal(String((receipt.lines[0] as Record<string,unknown>).test_name_snapshot),"Synthetic Phase Two Test");assert.equal(Number((receipt.lines[0] as Record<string,unknown>).unit_price_minor),10000);});
  await pool.end();
});
