export const PATIENT_ERROR_CODES = {
  PATIENT_NOT_FOUND: "PATIENT_NOT_FOUND",
  PATIENT_ACCESS_DENIED: "PATIENT_ACCESS_DENIED",
  PATIENT_NUMBER_DUPLICATE: "PATIENT_NUMBER_DUPLICATE",
  PATIENT_NATIONAL_ID_DUPLICATE: "PATIENT_NATIONAL_ID_DUPLICATE",
  PATIENT_INVALID_DOB: "PATIENT_INVALID_DOB",
  PATIENT_INVALID_AGE: "PATIENT_INVALID_AGE",
  PATIENT_INVALID_MOBILE: "PATIENT_INVALID_MOBILE",
  PATIENT_BRANCH_REQUIRED: "PATIENT_BRANCH_REQUIRED",
  PATIENT_BRANCH_INACTIVE: "PATIENT_BRANCH_INACTIVE",
  PATIENT_CROSS_TENANT: "PATIENT_CROSS_TENANT",
  PATIENT_DUPLICATE_WARNING: "PATIENT_DUPLICATE_WARNING",
  PATIENT_INACTIVE: "PATIENT_INACTIVE",
  PATIENT_VALIDATION: "PATIENT_VALIDATION",
  FORBIDDEN: "FORBIDDEN",
} as const;

export type PatientErrorCode = (typeof PATIENT_ERROR_CODES)[keyof typeof PATIENT_ERROR_CODES];

export const PATIENT_NUMBER_PREFIX = "PT";
export const MAX_ESTIMATED_AGE = 130;
export const MIN_ESTIMATED_AGE = 0;
