export const LAB_REPORT_RELEASE_ERROR_CODES = {
  LAB_REPORT_RELEASE_NOT_FOUND: "LAB_REPORT_RELEASE_NOT_FOUND",
  LAB_REPORT_RELEASE_ACCESS_DENIED: "LAB_REPORT_RELEASE_ACCESS_DENIED",
  LAB_REPORT_RELEASE_CROSS_TENANT: "LAB_REPORT_RELEASE_CROSS_TENANT",
  LAB_REPORT_RELEASE_BRANCH_ACCESS_DENIED: "LAB_REPORT_RELEASE_BRANCH_ACCESS_DENIED",
  LAB_REPORT_RELEASE_RESULT_NOT_VERIFIED: "LAB_REPORT_RELEASE_RESULT_NOT_VERIFIED",
  LAB_REPORT_RELEASE_CORRECTION_PENDING: "LAB_REPORT_RELEASE_CORRECTION_PENDING",
  LAB_REPORT_RELEASE_VERSION_MISMATCH: "LAB_REPORT_RELEASE_VERSION_MISMATCH",
  LAB_REPORT_RELEASE_ALREADY_RELEASED: "LAB_REPORT_RELEASE_ALREADY_RELEASED",
  LAB_REPORT_RELEASE_NOT_RELEASED: "LAB_REPORT_RELEASE_NOT_RELEASED",
  LAB_REPORT_RELEASE_INVALID_STATUS: "LAB_REPORT_RELEASE_INVALID_STATUS",
  LAB_REPORT_RELEASE_REPRINT_REASON_REQUIRED: "LAB_REPORT_RELEASE_REPRINT_REASON_REQUIRED",
  LAB_REPORT_RELEASE_WITHDRAWAL_REASON_REQUIRED: "LAB_REPORT_RELEASE_WITHDRAWAL_REASON_REQUIRED",
  LAB_REPORT_RELEASE_AMENDMENT_REASON_REQUIRED: "LAB_REPORT_RELEASE_AMENDMENT_REASON_REQUIRED",
  LAB_REPORT_RELEASE_PORTAL_ALREADY_PUBLISHED: "LAB_REPORT_RELEASE_PORTAL_ALREADY_PUBLISHED",
  LAB_REPORT_RELEASE_PORTAL_NOT_ELIGIBLE: "LAB_REPORT_RELEASE_PORTAL_NOT_ELIGIBLE",
  LAB_REPORT_RELEASE_VERIFICATION_TOKEN_INVALID: "LAB_REPORT_RELEASE_VERIFICATION_TOKEN_INVALID",
  LAB_REPORT_RELEASE_VERIFICATION_TOKEN_REVOKED: "LAB_REPORT_RELEASE_VERIFICATION_TOKEN_REVOKED",
  LAB_REPORT_RELEASE_VERIFICATION_TOKEN_EXPIRED: "LAB_REPORT_RELEASE_VERIFICATION_TOKEN_EXPIRED",
  LAB_REPORT_RELEASE_VALIDATION: "LAB_REPORT_RELEASE_VALIDATION",
} as const;

export type LabReportReleaseErrorCode =
  (typeof LAB_REPORT_RELEASE_ERROR_CODES)[keyof typeof LAB_REPORT_RELEASE_ERROR_CODES];
