export const PORTAL_ERROR_CODES = {
  PORTAL_INVALID_CREDENTIALS: "PORTAL_INVALID_CREDENTIALS",
  PORTAL_ACCOUNT_SUSPENDED: "PORTAL_ACCOUNT_SUSPENDED",
  PORTAL_ACCOUNT_NOT_VERIFIED: "PORTAL_ACCOUNT_NOT_VERIFIED",
  PORTAL_ACCOUNT_EXISTS: "PORTAL_ACCOUNT_EXISTS",
  PORTAL_USERNAME_TAKEN: "PORTAL_USERNAME_TAKEN",
  PORTAL_SESSION_EXPIRED: "PORTAL_SESSION_EXPIRED",
  PORTAL_NOT_AUTHENTICATED: "PORTAL_NOT_AUTHENTICATED",
  PORTAL_REPORT_NOT_ACCESSIBLE: "PORTAL_REPORT_NOT_ACCESSIBLE",
  PORTAL_PATIENT_NOT_FOUND: "PORTAL_PATIENT_NOT_FOUND",
  PORTAL_PATIENT_CONTACT_REQUIRED: "PORTAL_PATIENT_CONTACT_REQUIRED",
  PORTAL_PASSWORD_TOO_SHORT: "PORTAL_PASSWORD_TOO_SHORT",
  PORTAL_DELEGATION_EXISTS: "PORTAL_DELEGATION_EXISTS",
  PORTAL_DELEGATION_SELF: "PORTAL_DELEGATION_SELF",
  PORTAL_DELEGATION_REASON_REQUIRED: "PORTAL_DELEGATION_REASON_REQUIRED",
  PORTAL_DISABLED_FOR_TENANT: "PORTAL_DISABLED_FOR_TENANT",
  PORTAL_USERNAME_NOT_HELD: "PORTAL_USERNAME_NOT_HELD",
  PORTAL_USERNAME_MISMATCH: "PORTAL_USERNAME_MISMATCH",
  PORTAL_REASSIGN_SAME_PATIENT: "PORTAL_REASSIGN_SAME_PATIENT",
} as const;

export type PortalErrorCode = (typeof PORTAL_ERROR_CODES)[keyof typeof PORTAL_ERROR_CODES];
