import { notFound } from "next/navigation";
import { requirePrincipal } from "../../../../../lib/session";
import { getBillingRecord } from "../../../../../services/billing";
import { formatMinor } from "../../../../../domain/billing/money";
import { PrintControls } from "../../../../../components/billing/PrintControls";
export default async function ReceiptPage({params,searchParams}:{params:Promise<{type:string;id:string}>;searchParams:Promise<{copy?:string;format?:string}>}){const p=await requirePrincipal("receipts","read");const {type,id}=await params;if(!["bill","collection","refund"].includes(type))notFound();const record=await getBillingRecord(p.tenantId,type as "bill"|"collection"|"refund",id);const q=await searchParams;const b=record.bill as Record<string,unknown>;const format=["A4","A5","POS80","POS58"].includes(q.format??"")?q.format:String(b.receipt_format);const copy=["PATIENT","OFFICE","DUPLICATE"].includes(q.copy??"")?q.copy!:"PATIENT";const lines=record.lines as Record<string,unknown>[];const collections=record.collections as Record<string,unknown>[];const adjustments=record.adjustments as Record<string,unknown>[];const refunds=record.refunds as Record<string,unknown>[];const cancelled=adjustments.reduce((s,x)=>s+Number(x.amount_minor),0);const collected=collections.reduce((s,x)=>s+Number(x.amount_minor),0);const refunded=refunds.filter(x=>x.status==="PAID").reduce((s,x)=>s+Number(x.amount_minor),0);const balance=Number(b.net_minor)-cancelled-collected+refunded;const selectedCollection=type==="collection"?collections.find(x=>x.id===id):null;const selectedRefund=type==="refund"?refunds.find(x=>x.id===id):null;
return <main className={`receipt-sheet format-${format}`}><PrintControls billId={String(b.id)} receiptType={type.toUpperCase()} relatedId={type==="bill"?undefined:id} copy={copy} format={format as "A4"|"A5"|"POS80"|"POS58"}/><section className="receipt"><header className="receipt-header"><h1>{String(b.tenant_name)}</h1><p>{String(b.tenant_address??"")} {String(b.tenant_phone??"")}</p><h2>{type==="bill"?"Patient Bill":type==="collection"?"Due Collection Receipt":"Refund Receipt"}</h2><strong>{copy==="DUPLICATE"?"DUPLICATE / REPRINT":copy==="OFFICE"?"OFFICE COPY":"PATIENT COPY"}</strong></header><div className="receipt-meta"><p>Bill: {String(b.bill_number)}</p><p>Posted: {new Date(String(b.posted_at)).toLocaleString("en-BD")}</p><p>Patient: {String(b.patient_number_snapshot)} — {String(b.patient_name_snapshot)}</p><p>Mobile: {String(b.patient_mobile_snapshot??"")}</p>{Boolean(b.doctor_name_snapshot)&&<p>Referring doctor: {String(b.doctor_name_snapshot)}</p>}{Boolean(b.show_referral_partner_on_receipt)&&Boolean(b.referral_partner_name_snapshot)&&<p>Referral partner: {String(b.referral_partner_name_snapshot)}</p>}<p>Expected delivery: {b.expected_delivery_at?new Date(String(b.expected_delivery_at)).toLocaleString("en-BD"):"Not specified"}</p><p>Operator at posting: {String(b.operator_name)}</p></div>
{type==="bill"&&<><table><thead><tr><th>Test</th><th>Qty</th><th>Rate</th><th>Discount</th><th>Net</th></tr></thead><tbody>{lines.map(x=><tr key={String(x.id)}><td data-label="Test">{String(x.test_code_snapshot)} — {String(x.test_name_snapshot)}{Number(x.cancelled_minor)>0&&<strong> CANCELLED</strong>}</td><td data-label="Qty">{String(x.quantity)}</td><td data-label="Rate">{formatMinor(Number(x.unit_price_minor))}</td><td data-label="Discount">{formatMinor(Number(x.discount_minor))}</td><td data-label="Net">{formatMinor(Number(x.net_minor))}</td></tr>)}</tbody></table><div className="receipt-totals"><p>Original gross: {formatMinor(Number(b.gross_minor))}</p><p>Original discount: {formatMinor(Number(b.discount_minor))}</p><p>Original net: {formatMinor(Number(b.net_minor))}</p><p>Collections to print time: {formatMinor(collected)}</p><p>Cancellation adjustments: {formatMinor(cancelled)}</p><p>Paid refunds: {formatMinor(refunded)}</p><strong>{balance<0?"Remaining refundable credit":"Current amount due"}: {formatMinor(Math.abs(balance))}</strong></div></>}
{selectedCollection&&<div className="receipt-totals"><p>Collection: {String(selectedCollection.collection_number)}</p><p>Method: {String(selectedCollection.payment_method)}</p><p>Collector: {String(selectedCollection.collector_name)}</p><strong>Amount received: {formatMinor(Number(selectedCollection.amount_minor))}</strong><p>{balance<0?"Remaining refundable credit":"Current bill amount due"}: {formatMinor(Math.abs(balance))}</p></div>}
{selectedRefund&&<div className="receipt-totals"><p>Status: {String(selectedRefund.status)}</p><p>Payout method: {String(selectedRefund.payout_method)}</p><p>Payout reference: {String(selectedRefund.payout_reference)}</p><p>Paid by: {String(selectedRefund.payer_name)}</p><strong>Amount refunded: {formatMinor(Number(selectedRefund.amount_minor))}</strong></div>}
{b.status==="CANCELLED"&&<div className="cancelled-mark">CANCELLED BILL</div>}<footer><p>{String(b.receipt_footer??"")}</p><small>Recorded payment methods are operator declarations and do not imply gateway verification.</small></footer></section></main>}
