export const APPOINTMENT_ERROR_CODES = {
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  APPOINTMENT_ACCESS_DENIED: "APPOINTMENT_ACCESS_DENIED",
  APPOINTMENT_NUMBER_DUPLICATE: "APPOINTMENT_NUMBER_DUPLICATE",
  APPOINTMENT_INVALID_DATE: "APPOINTMENT_INVALID_DATE",
  APPOINTMENT_INVALID_SLOT: "APPOINTMENT_INVALID_SLOT",
  APPOINTMENT_SLOT_FULL: "APPOINTMENT_SLOT_FULL",
  APPOINTMENT_BRANCH_REQUIRED: "APPOINTMENT_BRANCH_REQUIRED",
  APPOINTMENT_BRANCH_INACTIVE: "APPOINTMENT_BRANCH_INACTIVE",
  APPOINTMENT_CROSS_TENANT: "APPOINTMENT_CROSS_TENANT",
  APPOINTMENT_PATIENT_INACTIVE: "APPOINTMENT_PATIENT_INACTIVE",
  APPOINTMENT_DOCTOR_INACTIVE: "APPOINTMENT_DOCTOR_INACTIVE",
  APPOINTMENT_INVALID_STATUS: "APPOINTMENT_INVALID_STATUS",
  APPOINTMENT_VALIDATION: "APPOINTMENT_VALIDATION",
  QUEUE_TOKEN_DUPLICATE: "QUEUE_TOKEN_DUPLICATE",
  FORBIDDEN: "FORBIDDEN",
} as const;

export type AppointmentErrorCode =
  (typeof APPOINTMENT_ERROR_CODES)[keyof typeof APPOINTMENT_ERROR_CODES];

export const APPOINTMENT_NUMBER_PREFIX = "AP";
export const DEFAULT_MAX_PATIENTS_PER_SLOT = 1;
