export const LAB_LIS_ERROR_CODES = {
  LAB_LIS_NOT_FOUND: "LAB_LIS_NOT_FOUND",
  LAB_LIS_MESSAGE_INVALID: "LAB_LIS_MESSAGE_INVALID",
  LAB_LIS_MESSAGE_CONTROL_ID_REQUIRED: "LAB_LIS_MESSAGE_CONTROL_ID_REQUIRED",
  LAB_LIS_SAMPLE_ID_REQUIRED: "LAB_LIS_SAMPLE_ID_REQUIRED",
  LAB_LIS_OBSERVATION_REQUIRED: "LAB_LIS_OBSERVATION_REQUIRED",
  LAB_LIS_DUPLICATE_MESSAGE: "LAB_LIS_DUPLICATE_MESSAGE",
  LAB_LIS_BRANCH_ACCESS_DENIED: "LAB_LIS_BRANCH_ACCESS_DENIED",
  LAB_LIS_ALREADY_PROCESSED: "LAB_LIS_ALREADY_PROCESSED",
  LAB_LIS_NOT_QUARANTINED: "LAB_LIS_NOT_QUARANTINED",
  LAB_LIS_RECONCILE_INPUT_REQUIRED: "LAB_LIS_RECONCILE_INPUT_REQUIRED",
  LAB_LIS_MAPPING_EXISTS: "LAB_LIS_MAPPING_EXISTS",
  LAB_LIS_MAPPING_SERVICE_INVALID: "LAB_LIS_MAPPING_SERVICE_INVALID",
  LAB_LIS_ANALYZER_INVALID: "LAB_LIS_ANALYZER_INVALID",
  LAB_LIS_OVERRIDE_NOT_PERMITTED: "LAB_LIS_OVERRIDE_NOT_PERMITTED",
  LAB_LIS_OVERRIDE_REASON_REQUIRED: "LAB_LIS_OVERRIDE_REASON_REQUIRED",
} as const;

export type LabLisErrorCode = (typeof LAB_LIS_ERROR_CODES)[keyof typeof LAB_LIS_ERROR_CODES];
