export const DOCTOR_SCHEDULE_ERROR_CODES = {
  DOCTOR_SCHEDULE_NOT_FOUND: "DOCTOR_SCHEDULE_NOT_FOUND",
  DOCTOR_SCHEDULE_DOCTOR_INVALID: "DOCTOR_SCHEDULE_DOCTOR_INVALID",
  DOCTOR_SCHEDULE_BRANCH_REQUIRED: "DOCTOR_SCHEDULE_BRANCH_REQUIRED",
  DOCTOR_SCHEDULE_BRANCH_ACCESS_DENIED: "DOCTOR_SCHEDULE_BRANCH_ACCESS_DENIED",
  DOCTOR_SCHEDULE_DOCTOR_NOT_AT_BRANCH: "DOCTOR_SCHEDULE_DOCTOR_NOT_AT_BRANCH",
  DOCTOR_SCHEDULE_INVALID_DAY: "DOCTOR_SCHEDULE_INVALID_DAY",
  DOCTOR_SCHEDULE_INVALID_TIME: "DOCTOR_SCHEDULE_INVALID_TIME",
  DOCTOR_SCHEDULE_INVALID_RANGE: "DOCTOR_SCHEDULE_INVALID_RANGE",
  DOCTOR_SCHEDULE_INVALID_SLOT_DURATION: "DOCTOR_SCHEDULE_INVALID_SLOT_DURATION",
  DOCTOR_SCHEDULE_OVERLAP: "DOCTOR_SCHEDULE_OVERLAP",
  DOCTOR_SCHEDULE_DUPLICATE: "DOCTOR_SCHEDULE_DUPLICATE",
  DOCTOR_SCHEDULE_HAS_BOOKINGS: "DOCTOR_SCHEDULE_HAS_BOOKINGS",
  DOCTOR_SCHEDULE_STALE: "DOCTOR_SCHEDULE_STALE",
  /** Doctor cannot be changed after schedule creation — retire and recreate instead. */
  DOCTOR_SCHEDULE_DOCTOR_IMMUTABLE: "DOCTOR_SCHEDULE_DOCTOR_IMMUTABLE",
} as const;

export type DoctorScheduleErrorCode =
  (typeof DOCTOR_SCHEDULE_ERROR_CODES)[keyof typeof DOCTOR_SCHEDULE_ERROR_CODES];
