export const MEDICATION_ERROR_CODES = {
  MEDICATION_NOT_FOUND: "MEDICATION_NOT_FOUND",
  MEDICATION_ACCESS_DENIED: "MEDICATION_ACCESS_DENIED",
  MEDICATION_DUPLICATE: "MEDICATION_DUPLICATE",
  MEDICATION_CODE_DUPLICATE: "MEDICATION_CODE_DUPLICATE",
  MEDICATION_BARCODE_DUPLICATE: "MEDICATION_BARCODE_DUPLICATE",
  MEDICATION_INVALID_STRENGTH: "MEDICATION_INVALID_STRENGTH",
  MEDICATION_GENERIC_REQUIRED: "MEDICATION_GENERIC_REQUIRED",
  MEDICATION_MANUFACTURER_INVALID: "MEDICATION_MANUFACTURER_INVALID",
  MEDICATION_BRANCH_INVALID: "MEDICATION_BRANCH_INVALID",
  MEDICATION_IN_USE: "MEDICATION_IN_USE",
  MEDICATION_STATUS_INVALID: "MEDICATION_STATUS_INVALID",
  GENERIC_DUPLICATE: "GENERIC_DUPLICATE",
  GENERIC_NOT_FOUND: "GENERIC_NOT_FOUND",
  MANUFACTURER_DUPLICATE: "MANUFACTURER_DUPLICATE",
  MANUFACTURER_NOT_FOUND: "MANUFACTURER_NOT_FOUND",
  MEDICATION_VALIDATION: "MEDICATION_VALIDATION",
  MEDICATION_IMPORT_INVALID: "MEDICATION_IMPORT_INVALID",
} as const;

export type MedicationErrorCode =
  (typeof MEDICATION_ERROR_CODES)[keyof typeof MEDICATION_ERROR_CODES];
