import type { PoolClient } from "pg";
import { transaction, query } from "../lib/db";
import { assertPermission, type SessionPrincipal } from "../lib/authorization";
import { calculateFinancialQuote, PAYMENT_METHODS, requestHash, requireNonNegativeMoney, requireOperationId, type PaymentMethod } from "../domain/billing/finance";

export type BillInput = { operationId:string; patientId:string; doctorId?:string; referralPartnerId?:string; expectedDeliveryAt?:string; lines:Array<{testId:string;lineKey:string;quantity:number;repeatReason?:string;unitPriceMinor?:number}>; discountType?:"NONE"|"PERCENTAGE"|"FIXED_AMOUNT"; discountValue?:string; payments?:Array<{amount:string;method:PaymentMethod;reference?:string}>; originDeviceId?:string; localReceiptNumber?:string; catalogVersion?:string };
type StoredResponse = Record<string, unknown> & { idempotent?: boolean };
type BillingResponse = StoredResponse & { billId?:string; billNumber?:string; collectionId?:string; collectionNumber?:string; refundId?:string; status?:string; grossMinor?:number; discountMinor?:number; netMinor?:number; paidMinor?:number; dueMinor?:number; amountMinor?:number; balanceMinor?:number; refundableMinor?:number; cancelledMinor?:number };

function appError(message:string,status=400) { const error=new Error(message) as Error&{status?:number}; error.status=status; return error; }

async function claim(client:PoolClient, tenantId:string, operationId:string, operationType:string, payload:unknown) {
  requireOperationId(operationId); const hash=requestHash(payload);
  await client.query(`insert into billing_requests(tenant_id,operation_id,operation_type,request_hash) values($1,$2,$3,$4) on conflict do nothing`,[tenantId,operationId,operationType,hash]);
  const row=(await client.query<{request_hash:string;operation_type:string;response_json:StoredResponse|null}>(`select request_hash,operation_type,response_json from billing_requests where tenant_id=$1 and operation_id=$2 for update`,[tenantId,operationId])).rows[0];
  if (!row || row.request_hash!==hash || row.operation_type!==operationType) throw appError("Idempotency key was already used with different content",409);
  return row.response_json ? {...row.response_json,idempotent:true} : null;
}

async function complete(client:PoolClient, tenantId:string, operationId:string, entityId:string, response:StoredResponse) {
  await client.query(`update billing_requests set entity_id=$3,response_json=$4,completed_at=now() where tenant_id=$1 and operation_id=$2`,[tenantId,operationId,entityId,JSON.stringify(response)]);
}

async function lockedBalance(client:PoolClient, tenantId:string, billId:string) {
  const bill=(await client.query<{id:string;net_minor:string;status:string}>(`select id,net_minor::text,status from bills where tenant_id=$1 and id=$2 for update`,[tenantId,billId])).rows[0];
  if (!bill) throw appError("Bill not found",404);
  const totals=(await client.query<{cancelled:string;collected:string;refunded:string;reserved:string}>(`select
    coalesce((select sum(amount_minor) from bill_adjustments where tenant_id=$1 and bill_id=$2),0)::text cancelled,
    coalesce((select sum(amount_minor) from collections where tenant_id=$1 and bill_id=$2),0)::text collected,
    coalesce((select sum(amount_minor) from refunds where tenant_id=$1 and bill_id=$2 and status='PAID'),0)::text refunded,
    coalesce((select sum(amount_minor) from refunds where tenant_id=$1 and bill_id=$2 and status in ('REQUESTED','APPROVED')),0)::text reserved`,[tenantId,billId])).rows[0];
  const adjustedNet=Number(bill.net_minor)-Number(totals.cancelled), collected=Number(totals.collected), refunded=Number(totals.refunded);
  return {bill,adjustedNet,collected,refunded,reserved:Number(totals.reserved),balance:adjustedNet-collected+refunded,refundable:Math.max(0,collected-refunded-adjustedNet)};
}

function assertPaymentMethod(method:string):asserts method is PaymentMethod { if (!(PAYMENT_METHODS as readonly string[]).includes(method)) throw new Error("Unsupported payment method"); }

export async function postBill(principal:SessionPrincipal,input:BillInput):Promise<BillingResponse> {
  assertPermission(principal,"billing","create");
  return transaction(async client=>{
    const replay=await claim(client,principal.tenantId,input.operationId,"POST_BILL",input); if(replay)return replay;
    const tenant=(await client.query<{currency_code:string;counter_discount_limit_bps:number;admin_discount_limit_bps:number}>(`select currency_code,counter_discount_limit_bps,admin_discount_limit_bps from tenants where id=$1`,[principal.tenantId])).rows[0];
    const patient=(await client.query<{patient_number:string;full_name:string;mobile:string|null}>(`select patient_number,full_name,mobile from patients where tenant_id=$1 and id=$2 and is_active`,[principal.tenantId,input.patientId])).rows[0]; if(!patient)throw appError("Patient not found",404);
    const doctor=input.doctorId?(await client.query<{name:string}>(`select name from doctors where tenant_id=$1 and id=$2 and is_active`,[principal.tenantId,input.doctorId])).rows[0]:null; if(input.doctorId&&!doctor)throw appError("Doctor not found",404);
    const partner=input.referralPartnerId?(await client.query<{name:string}>(`select name from referral_partners where tenant_id=$1 and id=$2 and is_active`,[principal.tenantId,input.referralPartnerId])).rows[0]:null; if(input.referralPartnerId&&!partner)throw appError("Referral partner not found",404);
    if(!input.lines.length)throw new Error("At least one test is required");
    const ids=input.lines.map(line=>line.testId); const tests=await client.query<{id:string;code:string;name:string;price:string;group_name:string}>(`select t.id,t.code,t.name,t.price::text,g.name group_name from tenant_tests t join test_groups g on g.tenant_id=t.tenant_id and g.id=t.group_id where t.tenant_id=$1 and t.id=any($2::uuid[]) and t.is_active`,[principal.tenantId,ids]);
    const byId=new Map(tests.rows.map(test=>[test.id,test])); if(byId.size!==new Set(ids).size)throw new Error("One or more tests are invalid");
    const seen=new Map<string,number>(); for(const line of input.lines){seen.set(line.testId,(seen.get(line.testId)??0)+1); if((seen.get(line.testId)??0)>1&&!line.repeatReason?.trim())throw new Error("Intentional repeated tests require a reason");}
    if(input.originDeviceId){if(!input.catalogVersion)throw new Error("Offline bill catalog authorization is required");const snapshot=(await client.query<{catalog_json:Array<{id:string;code:string;name:string;groupName:string;priceMinor:number}>}>(`select catalog_json from device_catalog_snapshots where tenant_id=$1 and device_id=$2 and version=$3`,[principal.tenantId,input.originDeviceId,input.catalogVersion])).rows[0];if(!snapshot)throw appError("Offline catalog authorization is unknown",409);for(const item of snapshot.catalog_json){if(byId.has(item.id))byId.set(item.id,{id:item.id,code:item.code,name:item.name,group_name:item.groupName,price:(item.priceMinor/100).toFixed(2)});}}
    const ordered=input.lines.map(line=>{const test=byId.get(line.testId);if(!test)throw new Error("Test does not belong to tenant");if(input.originDeviceId&&line.unitPriceMinor!==requireNonNegativeMoney(test.price,"Authorized price"))throw appError("Offline price does not match the authorized catalog snapshot",409);return {line,test};});
    const prices=ordered.map(({test})=>requireNonNegativeMoney(test.price,"Configured price")); const quantities=ordered.map(({line})=>line.quantity);
    const quote=calculateFinancialQuote({prices,quantities,discountType:input.discountType,discountValue:input.discountValue});
    const usedBps=quote.gross?Math.ceil(quote.discount*10000/quote.gross):0; const canApprove=principal.permissions.has("discount:approve");
    if(usedBps>tenant.admin_discount_limit_bps||(!canApprove&&usedBps>tenant.counter_discount_limit_bps))throw appError("Discount exceeds authorized limit",403);
    const payments=(input.payments??[]).map(payment=>{assertPaymentMethod(payment.method);return {...payment,minor:requireNonNegativeMoney(payment.amount,"Payment")};});
    if(payments.some(payment=>payment.minor<=0))throw new Error("Payment must be greater than zero"); const paid=payments.reduce((sum,p)=>sum+p.minor,0); if(paid>quote.net)throw new Error("Initial payment exceeds net payable");
    await client.query(`insert into billing_counters(tenant_id,branch_id) values($1,$2) on conflict do nothing`,[principal.tenantId,principal.branchId]);
    const counter=(await client.query<{value:string}>(`update billing_counters set next_bill_number=next_bill_number+1 where tenant_id=$1 and branch_id=$2 returning (next_bill_number-1)::text value`,[principal.tenantId,principal.branchId])).rows[0]; if(!counter)throw new Error("Unable to allocate bill number");
    const branch=(await client.query<{code:string}>(`select code from branches where tenant_id=$1 and id=$2`,[principal.tenantId,principal.branchId])).rows[0];
    const billNumber=`${branch.code}-${new Date().getUTCFullYear()}-${counter.value.padStart(6,"0")}`;
    if(Boolean(input.originDeviceId)!==Boolean(input.localReceiptNumber))throw new Error("Device origin and local receipt must be supplied together");
    if(input.originDeviceId){const device=await client.query(`select 1 from devices where tenant_id=$1 and branch_id=$2 and id=$3`,[principal.tenantId,principal.branchId,input.originDeviceId]);if(!device.rowCount)throw appError("Device does not belong to tenant and branch",403);}
    const bill=(await client.query<{id:string}>(`insert into bills(tenant_id,branch_id,operation_id,bill_number,patient_id,doctor_id,referral_partner_id,patient_number_snapshot,patient_name_snapshot,patient_mobile_snapshot,doctor_name_snapshot,referral_partner_name_snapshot,currency_code,gross_minor,discount_minor,net_minor,expected_delivery_at,posted_by,origin_device_id,local_receipt_number) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) returning id`,[principal.tenantId,principal.branchId,input.operationId,billNumber,input.patientId,input.doctorId??null,input.referralPartnerId??null,patient.patient_number,patient.full_name,patient.mobile,doctor?.name??null,partner?.name??null,tenant.currency_code,quote.gross,quote.discount,quote.net,input.expectedDeliveryAt||null,principal.userId,input.originDeviceId??null,input.localReceiptNumber??null])).rows[0];
    for(let index=0;index<ordered.length;index++){const {line,test}=ordered[index];const amounts=quote.lines[index];await client.query(`insert into bill_lines(tenant_id,bill_id,tenant_test_id,line_key,test_code_snapshot,test_name_snapshot,group_name_snapshot,quantity,unit_price_minor,gross_minor,discount_minor,net_minor,repeat_reason) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[principal.tenantId,bill.id,test.id,line.lineKey,test.code,test.name,test.group_name,line.quantity,prices[index],amounts.gross,amounts.discount,amounts.net,line.repeatReason??null]);}
    for(let index=0;index<payments.length;index++){const payment=payments[index];await client.query(`insert into collections(tenant_id,branch_id,bill_id,operation_id,collection_number,kind,amount_minor,payment_method,external_reference,collected_by) values($1,$2,$3,$4,$5,'INITIAL',$6,$7,$8,$9)`,[principal.tenantId,principal.branchId,bill.id,`${input.operationId}_initial_${index}`,`${billNumber}-C${index+1}`,payment.minor,payment.method,payment.reference??null,principal.userId]);}
    const response={billId:bill.id,billNumber,grossMinor:quote.gross,discountMinor:quote.discount,netMinor:quote.net,paidMinor:paid,dueMinor:quote.net-paid}; await complete(client,principal.tenantId,input.operationId,bill.id,response); return response;
  });
}

export async function collectDue(principal:SessionPrincipal,input:{operationId:string;billId:string;amount:string;method:PaymentMethod;reference?:string}):Promise<BillingResponse>{
  assertPermission(principal,"billing","update"); assertPaymentMethod(input.method);
  return transaction(async client=>{const replay=await claim(client,principal.tenantId,input.operationId,"COLLECT_DUE",input);if(replay)return replay;const state=await lockedBalance(client,principal.tenantId,input.billId);const amount=requireNonNegativeMoney(input.amount,"Collection");if(amount<=0||amount>Math.max(0,state.balance))throw appError("Collection exceeds outstanding balance",409);const count=await client.query(`select count(*)::int count from collections where tenant_id=$1 and bill_id=$2`,[principal.tenantId,input.billId]);const bill=await client.query<{bill_number:string}>(`select bill_number from bills where tenant_id=$1 and id=$2`,[principal.tenantId,input.billId]);const row=(await client.query<{id:string;collection_number:string}>(`insert into collections(tenant_id,branch_id,bill_id,operation_id,collection_number,kind,amount_minor,payment_method,external_reference,collected_by) values($1,$2,$3,$4,$5,'DUE',$6,$7,$8,$9) returning id,collection_number`,[principal.tenantId,principal.branchId,input.billId,input.operationId,`${bill.rows[0].bill_number}-C${Number(count.rows[0].count)+1}`,amount,input.method,input.reference??null,principal.userId])).rows[0];const response={collectionId:row.id,collectionNumber:row.collection_number,amountMinor:amount,balanceMinor:state.balance-amount};await complete(client,principal.tenantId,input.operationId,row.id,response);return response;});
}

export async function cancelBill(principal:SessionPrincipal,input:{operationId:string;billId:string;lineIds?:string[];reason:string}):Promise<BillingResponse>{
  assertPermission(principal,"billing_adjustment","approve");if(!input.reason.trim())throw new Error("Cancellation reason is required");
  return transaction(async client=>{const replay=await claim(client,principal.tenantId,input.operationId,"CANCEL",input);if(replay)return replay;await lockedBalance(client,principal.tenantId,input.billId);const explicitlySelected=Boolean(input.lineIds?.length);const lines=await client.query<{id:string;net_minor:string;cancelled_minor:string}>(`select id,net_minor::text,cancelled_minor::text from bill_lines where tenant_id=$1 and bill_id=$2 and ($3::uuid[] is null or id=any($3::uuid[])) order by id for update`,[principal.tenantId,input.billId,explicitlySelected?input.lineIds:null]);if(!lines.rowCount)throw new Error("No eligible bill lines");let total=0;for(const line of lines.rows){const remaining=Number(line.net_minor)-Number(line.cancelled_minor);if(remaining<=0){if(explicitlySelected)throw appError("A selected line is already fully cancelled",409);continue;}total+=remaining;await client.query(`update bill_lines set cancelled_minor=cancelled_minor+$3 where tenant_id=$1 and id=$2`,[principal.tenantId,line.id,remaining]);await client.query(`insert into bill_adjustments(tenant_id,branch_id,bill_id,bill_line_id,operation_id,adjustment_type,amount_minor,reason,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[principal.tenantId,principal.branchId,input.billId,line.id,input.operationId,explicitlySelected?"CANCEL_LINE":"CANCEL_BILL",remaining,input.reason.trim(),principal.userId]);}if(total===0)throw appError("Bill is already fully cancelled",409);const remaining=(await client.query<{amount:string}>(`select sum(net_minor-cancelled_minor)::text amount from bill_lines where tenant_id=$1 and bill_id=$2`,[principal.tenantId,input.billId])).rows[0].amount;await client.query(`update bills set status=$3,version=version+1 where tenant_id=$1 and id=$2`,[principal.tenantId,input.billId,Number(remaining)===0?"CANCELLED":"PARTIALLY_CANCELLED"]);const state=await lockedBalance(client,principal.tenantId,input.billId);const response={billId:input.billId,cancelledMinor:total,balanceMinor:state.balance,refundableMinor:state.refundable};await complete(client,principal.tenantId,input.operationId,input.billId,response);return response;});
}

export async function requestRefund(principal:SessionPrincipal,input:{operationId:string;billId:string;amount:string;reason:string}):Promise<BillingResponse>{
  assertPermission(principal,"refund","create");if(!input.reason.trim())throw new Error("Refund reason is required");
  return transaction(async client=>{const replay=await claim(client,principal.tenantId,input.operationId,"REFUND_REQUEST",input);if(replay)return replay;const state=await lockedBalance(client,principal.tenantId,input.billId);const amount=requireNonNegativeMoney(input.amount,"Refund");if(amount<=0||amount>state.refundable-state.reserved)throw appError("Refund exceeds available refundable credit",409);const row=(await client.query<{id:string}>(`insert into refunds(tenant_id,branch_id,bill_id,request_operation_id,amount_minor,reason,requested_by) values($1,$2,$3,$4,$5,$6,$7) returning id`,[principal.tenantId,principal.branchId,input.billId,input.operationId,amount,input.reason.trim(),principal.userId])).rows[0];const response={refundId:row.id,status:"REQUESTED",amountMinor:amount};await complete(client,principal.tenantId,input.operationId,row.id,response);return response;});
}

export async function decideRefund(principal:SessionPrincipal,input:{operationId:string;refundId:string;approve:boolean;reason?:string}):Promise<BillingResponse>{
  assertPermission(principal,"refund","approve");return transaction(async client=>{const replay=await claim(client,principal.tenantId,input.operationId,"REFUND_DECISION",input);if(replay)return replay;const basic=(await client.query<{bill_id:string}>(`select bill_id from refunds where tenant_id=$1 and id=$2`,[principal.tenantId,input.refundId])).rows[0];if(!basic)throw appError("Refund not found",404);await lockedBalance(client,principal.tenantId,basic.bill_id);const refund=(await client.query<{status:string;requested_by:string}>(`select status,requested_by from refunds where tenant_id=$1 and id=$2 for update`,[principal.tenantId,input.refundId])).rows[0];if(refund.status!=="REQUESTED")throw appError("Refund request was already decided",409);if(refund.requested_by===principal.userId)throw appError("Refund maker cannot approve their own request",403);const status=input.approve?"APPROVED":"REJECTED";await client.query(`update refunds set status=$3,decided_by=$4,decided_at=now(),decision_reason=$5 where tenant_id=$1 and id=$2`,[principal.tenantId,input.refundId,status,principal.userId,input.reason??null]);const response={refundId:input.refundId,status};await complete(client,principal.tenantId,input.operationId,input.refundId,response);return response;});
}

export async function payRefund(principal:SessionPrincipal,input:{operationId:string;refundId:string;method:PaymentMethod;reference:string}):Promise<BillingResponse>{
  assertPermission(principal,"refund","update");assertPaymentMethod(input.method);if(!input.reference.trim())throw new Error("Payout reference is required");
  return transaction(async client=>{const replay=await claim(client,principal.tenantId,input.operationId,"REFUND_PAYOUT",input);if(replay)return replay;const basic=(await client.query<{bill_id:string}>(`select bill_id from refunds where tenant_id=$1 and id=$2`,[principal.tenantId,input.refundId])).rows[0];if(!basic)throw appError("Refund not found",404);const state=await lockedBalance(client,principal.tenantId,basic.bill_id);const refund=(await client.query<{status:string;amount_minor:string}>(`select status,amount_minor::text from refunds where tenant_id=$1 and id=$2 for update`,[principal.tenantId,input.refundId])).rows[0];if(refund.status!=="APPROVED")throw appError("Only approved refunds can be paid",409);if(Number(refund.amount_minor)>state.refundable)throw appError("Refund exceeds current refundable credit",409);await client.query(`update refunds set status='PAID',payout_operation_id=$3,payout_method=$4,payout_reference=$5,paid_by=$6,paid_at=now() where tenant_id=$1 and id=$2`,[principal.tenantId,input.refundId,input.operationId,input.method,input.reference.trim(),principal.userId]);const response={refundId:input.refundId,status:"PAID",amountMinor:Number(refund.amount_minor)};await complete(client,principal.tenantId,input.operationId,input.refundId,response);return response;});
}

export async function saveDraft(principal:SessionPrincipal,input:{operationId:string;patientId?:string;payload:unknown}){assertPermission(principal,"billing","create");requireOperationId(input.operationId);return(await query<{id:string}>(`insert into billing_drafts(tenant_id,branch_id,operation_id,patient_id,payload,created_by) values($1,$2,$3,$4,$5,$6) on conflict(tenant_id,operation_id) do update set patient_id=excluded.patient_id,payload=excluded.payload,updated_at=now() where billing_drafts.status='HELD' returning id`,[principal.tenantId,principal.branchId,input.operationId,input.patientId??null,JSON.stringify(input.payload),principal.userId])).rows[0];}
export async function cancelDraft(principal:SessionPrincipal,draftId:string){assertPermission(principal,"billing","create");const result=await query(`update billing_drafts set status='CANCELLED',updated_at=now() where tenant_id=$1 and id=$2 and status='HELD'`,[principal.tenantId,draftId]);if(!result.rowCount)throw appError("Held draft not found",404);}

export async function searchBillingContext(tenantId:string,term=""){
  const like=`%${term.trim()}%`;const [patients,tests,doctors,partners,drafts]=await Promise.all([
    query(`select id,patient_number,full_name,mobile from patients where tenant_id=$1 and is_active and ($2='' or lower(full_name) like lower($3) or patient_number=upper($2) or coalesce(mobile,'') like $3) order by full_name limit 50`,[tenantId,term.trim(),like]),
    query(`select t.id,t.code,t.name,t.price::text,g.name group_name from tenant_tests t join test_groups g on g.tenant_id=t.tenant_id and g.id=t.group_id where t.tenant_id=$1 and t.is_active and ($2='' or lower(t.name) like lower($3) or lower(t.code) like lower($3) or lower(g.name) like lower($3)) order by t.code limit 100`,[tenantId,term.trim(),like]),
    query(`select id,code,name from doctors where tenant_id=$1 and is_active order by name`,[tenantId]),query(`select id,code,name,type from referral_partners where tenant_id=$1 and is_active order by name`,[tenantId]),query(`select id,operation_id,payload,updated_at from billing_drafts where tenant_id=$1 and status='HELD' order by updated_at desc limit 20`,[tenantId])]);return{patients:patients.rows,tests:tests.rows,doctors:doctors.rows,partners:partners.rows,drafts:drafts.rows};
}

export async function findBills(tenantId:string,term="") {const like=`%${term.trim()}%`;return(await query(`select b.id,b.bill_number,b.patient_name_snapshot,b.patient_mobile_snapshot,b.net_minor::text,b.status,b.posted_at,coalesce(sum(c.amount_minor),0)::text collected_minor,coalesce((select sum(a.amount_minor) from bill_adjustments a where a.tenant_id=b.tenant_id and a.bill_id=b.id),0)::text adjusted_minor,coalesce((select sum(r.amount_minor) from refunds r where r.tenant_id=b.tenant_id and r.bill_id=b.id and r.status='PAID'),0)::text refunded_minor from bills b left join collections c on c.tenant_id=b.tenant_id and c.bill_id=b.id where b.tenant_id=$1 and ($2='' or b.bill_number ilike $3 or b.patient_name_snapshot ilike $3 or coalesce(b.patient_mobile_snapshot,'') ilike $3) group by b.id order by b.posted_at desc limit 100`,[tenantId,term.trim(),like])).rows;}

export async function getBillingRecord(tenantId:string, entityType:"bill"|"collection"|"refund", entityId:string) {
  let billId=entityId; if(entityType==="collection")billId=(await query<{bill_id:string}>(`select bill_id from collections where tenant_id=$1 and id=$2`,[tenantId,entityId])).rows[0]?.bill_id; if(entityType==="refund")billId=(await query<{bill_id:string}>(`select bill_id from refunds where tenant_id=$1 and id=$2`,[tenantId,entityId])).rows[0]?.bill_id; if(!billId)throw appError("Receipt not found",404);
  const [bill,lines,collections,adjustments,refunds]=await Promise.all([
    query(`select b.*,t.name tenant_name,t.address tenant_address,t.phone tenant_phone,t.email tenant_email,t.logo_url,t.receipt_footer,t.receipt_format,t.show_referral_partner_on_receipt,br.name branch_name,br.address branch_address,u.display_name operator_name from bills b join tenants t on t.id=b.tenant_id join branches br on br.tenant_id=b.tenant_id and br.id=b.branch_id join users u on u.tenant_id=b.tenant_id and u.id=b.posted_by where b.tenant_id=$1 and b.id=$2`,[tenantId,billId]),
    query(`select * from bill_lines where tenant_id=$1 and bill_id=$2 order by created_at,id`,[tenantId,billId]),
    query(`select c.*,u.display_name collector_name from collections c join users u on u.tenant_id=c.tenant_id and u.id=c.collected_by where c.tenant_id=$1 and c.bill_id=$2 order by c.collected_at,c.id`,[tenantId,billId]),
    query(`select a.*,u.display_name actor_name from bill_adjustments a join users u on u.tenant_id=a.tenant_id and u.id=a.created_by where a.tenant_id=$1 and a.bill_id=$2 order by a.created_at`,[tenantId,billId]),
    query(`select r.*,rq.display_name requester_name,dc.display_name decider_name,py.display_name payer_name from refunds r join users rq on rq.tenant_id=r.tenant_id and rq.id=r.requested_by left join users dc on dc.tenant_id=r.tenant_id and dc.id=r.decided_by left join users py on py.tenant_id=r.tenant_id and py.id=r.paid_by where r.tenant_id=$1 and r.bill_id=$2 order by r.requested_at`,[tenantId,billId]),
  ]);if(!bill.rowCount)throw appError("Receipt not found",404);return{entityType,entityId,bill:bill.rows[0],lines:lines.rows,collections:collections.rows,adjustments:adjustments.rows,refunds:refunds.rows};
}

export async function dailyCollectionReport(tenantId:string,input:{date:string;branchId?:string;cashierId?:string;method?:string}) {
  if(!/^\d{4}-\d{2}-\d{2}$/.test(input.date))throw new Error("Invalid report date"); if(input.method)assertPaymentMethod(input.method);
  const bounds=(await query<{start_at:string;end_at:string;timezone:string}>(`select ($2::date::timestamp at time zone timezone)::text start_at,(($2::date+1)::timestamp at time zone timezone)::text end_at,timezone from tenants where id=$1`,[tenantId,input.date])).rows[0];if(!bounds)throw appError("Tenant not found",404);
  const params=[tenantId,bounds.start_at,bounds.end_at,input.branchId||null,input.cashierId||null,input.method||null];
  const bills=await query(`select b.id,b.bill_number,b.patient_name_snapshot,b.net_minor::text,b.posted_at,u.display_name cashier,br.name branch from bills b join users u on u.tenant_id=b.tenant_id and u.id=b.posted_by join branches br on br.tenant_id=b.tenant_id and br.id=b.branch_id where b.tenant_id=$1 and b.posted_at >= $2::timestamptz and b.posted_at < $3::timestamptz and ($4::uuid is null or b.branch_id=$4) and ($5::uuid is null or b.posted_by=$5) order by b.posted_at`,params.slice(0,5));
  const collections=await query(`select c.id,c.collection_number,c.amount_minor::text,c.payment_method,c.kind,c.collected_at,b.bill_number,b.posted_at bill_posted_at,u.display_name cashier,br.name branch from collections c join bills b on b.tenant_id=c.tenant_id and b.id=c.bill_id join users u on u.tenant_id=c.tenant_id and u.id=c.collected_by join branches br on br.tenant_id=c.tenant_id and br.id=c.branch_id where c.tenant_id=$1 and c.collected_at >= $2::timestamptz and c.collected_at < $3::timestamptz and ($4::uuid is null or c.branch_id=$4) and ($5::uuid is null or c.collected_by=$5) and ($6::text is null or c.payment_method=$6) order by c.collected_at`,params);
  const refunds=await query(`select r.id,r.amount_minor::text,r.payout_method,r.payout_reference,r.paid_at,b.bill_number,u.display_name cashier,br.name branch from refunds r join bills b on b.tenant_id=r.tenant_id and b.id=r.bill_id join users u on u.tenant_id=r.tenant_id and u.id=r.paid_by join branches br on br.tenant_id=r.tenant_id and br.id=r.branch_id where r.tenant_id=$1 and r.status='PAID' and r.paid_at >= $2::timestamptz and r.paid_at < $3::timestamptz and ($4::uuid is null or r.branch_id=$4) and ($5::uuid is null or r.paid_by=$5) and ($6::text is null or r.payout_method=$6) order by r.paid_at`,params);
  const billValue=bills.rows.reduce((sum,row)=>sum+Number(row.net_minor),0);let initial=0,oldDue=0;for(const row of collections.rows){if(new Date(String(row.bill_posted_at))>=new Date(bounds.start_at))initial+=Number(row.amount_minor);else oldDue+=Number(row.amount_minor);}const paidRefunds=refunds.rows.reduce((sum,row)=>sum+Number(row.amount_minor),0);
  const position=(await query<{outstanding:string;credit:string}>(`select coalesce(sum(greatest(balance,0)),0)::text outstanding,coalesce(sum(greatest(-balance,0)),0)::text credit from (select b.net_minor-coalesce(a.amount,0)-coalesce(c.amount,0)+coalesce(r.amount,0) balance from bills b left join (select tenant_id,bill_id,sum(amount_minor) amount from bill_adjustments group by tenant_id,bill_id) a on a.tenant_id=b.tenant_id and a.bill_id=b.id left join (select tenant_id,bill_id,sum(amount_minor) amount from collections group by tenant_id,bill_id) c on c.tenant_id=b.tenant_id and c.bill_id=b.id left join (select tenant_id,bill_id,sum(amount_minor) amount from refunds where status='PAID' group by tenant_id,bill_id) r on r.tenant_id=b.tenant_id and r.bill_id=b.id where b.tenant_id=$1 and ($2::uuid is null or b.branch_id=$2)) positions`,[tenantId,input.branchId||null])).rows[0];
  return{date:input.date,timezone:bounds.timezone,startAt:bounds.start_at,endAt:bounds.end_at,totals:{billValueMinor:billValue,initialCollectionsMinor:initial,oldDueCollectionsMinor:oldDue,paidRefundsMinor:paidRefunds,netCollectionMinor:initial+oldDue-paidRefunds,outstandingReceivablesMinor:Number(position.outstanding),refundableCreditMinor:Number(position.credit)},bills:bills.rows,collections:collections.rows,refunds:refunds.rows};
}
