import { createHash, createHmac, randomBytes, sign, verify } from "node:crypto";
import { query, transaction } from "../lib/db";
import { assertPermission, loadPermissions, permissionKey, type SessionPrincipal } from "../lib/authorization";
import { verifyPassword } from "../lib/password";
import { requestHash, requireNonNegativeMoney } from "../domain/billing/finance";
import { collectDue, postBill, type BillInput } from "./billing";

type DeviceRow={id:string;tenant_id:string;branch_id:string;installation_id:string;secret_hash:string;status:"ACTIVE"|"DISABLED"|"REVOKED";authorization_epoch:number};
export type DeviceContext={device:DeviceRow};
export type LeaseClaims={version:1;deviceId:string;tenantId:string;branchId:string;userId:string;username:string;displayName:string;permissions:string[];authorizationVersion:string;catalogVersion:string;issuedAt:string;expiresAt:string;deviceEpoch:number};
export type SyncEnvelope={contractVersion:1;operationId:string;operationType:"CREATE_PATIENT"|"POST_BILL"|"REQUEST_CANCELLATION"|"REQUEST_REFUND";tenantId:string;branchId:string;deviceId:string;actorUserId:string;occurredAtUtc:string;businessDate:string;leaseToken:string;dependencies:string[];payload:Record<string,unknown>};

function appError(message:string,status=400){const error=new Error(message) as Error&{status?:number};error.status=status;return error;}
function required(name:string){const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;}
function secretDigest(value:string){return createHmac("sha256",required("DEVICE_AUTH_PEPPER")).update(value).digest("hex");}
function b64(value:Buffer|string){return Buffer.from(value).toString("base64url");}
function signingPrivateKey(){return Buffer.from(required("DEVICE_LEASE_PRIVATE_KEY_PEM_BASE64"),"base64").toString("utf8");}
function signingPublicKey(){return Buffer.from(required("DEVICE_LEASE_PUBLIC_KEY_PEM_BASE64"),"base64").toString("utf8");}
function safeText(value:unknown,label:string,max=200){const text=String(value??"").trim();if(!text||text.length>max)throw new Error(`Invalid ${label}`);return text;}
function normalizePhone(value:unknown){return String(value??"").replace(/\D/g,"")||null;}

export function signLease(claims:LeaseClaims){const encoded=b64(JSON.stringify(claims));return `${encoded}.${sign(null,Buffer.from(encoded),signingPrivateKey()).toString("base64url")}`;}
export function verifyLease(token:string):LeaseClaims{const [encoded,signature,extra]=token.split(".");if(!encoded||!signature||extra||!verify(null,Buffer.from(encoded),signingPublicKey(),Buffer.from(signature,"base64url")))throw appError("Invalid offline authorization lease",401);const claims=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8")) as LeaseClaims;if(claims.version!==1)throw appError("Unsupported authorization lease",409);return claims;}

async function authorizationVersion(tenantId:string,userId:string,authEpoch?:number){const permissions=[...(await loadPermissions(tenantId,userId))].sort();let epoch=authEpoch;if(epoch===undefined)epoch=(await query<{auth_epoch:number}>(`select auth_epoch from users where tenant_id=$1 and id=$2`,[tenantId,userId])).rows[0]?.auth_epoch;return {permissions,version:createHash("sha256").update(JSON.stringify({epoch,permissions})).digest("hex")};}

async function catalogSnapshot(tenantId:string){const rows=(await query<{id:string;code:string;name:string;group_name:string;price:string;is_active:boolean}>(`select t.id,t.code,t.name,g.name group_name,t.price::text,t.is_active from tenant_tests t join test_groups g on g.tenant_id=t.tenant_id and g.id=t.group_id where t.tenant_id=$1 and t.is_active order by t.id`,[tenantId])).rows;const catalog=rows.map(row=>({id:row.id,code:row.code,name:row.name,groupName:row.group_name,priceMinor:requireNonNegativeMoney(row.price,"Catalog price"),isActive:row.is_active}));return {catalog,version:requestHash(catalog)};}

async function issueUserLease(device:DeviceRow,user:{id:string;username:string;display_name:string;auth_epoch:number},catalogVersion:string){const auth=await authorizationVersion(device.tenant_id,user.id,user.auth_epoch);const hours=(await query<{offline_lease_hours:number}>(`select offline_lease_hours from tenants where id=$1`,[device.tenant_id])).rows[0].offline_lease_hours;const issued=new Date();const claims:LeaseClaims={version:1,deviceId:device.id,tenantId:device.tenant_id,branchId:device.branch_id,userId:user.id,username:user.username,displayName:user.display_name,permissions:auth.permissions,authorizationVersion:auth.version,catalogVersion,issuedAt:issued.toISOString(),expiresAt:new Date(issued.getTime()+hours*3600000).toISOString(),deviceEpoch:device.authorization_epoch};return {claims,token:signLease(claims)};}

export async function issueActivationCode(principal:SessionPrincipal,input:{branchId:string;expiresInMinutes?:number}){assertPermission(principal,"devices","create");const branch=await query(`select 1 from branches where tenant_id=$1 and id=$2 and is_active`,[principal.tenantId,input.branchId]);if(!branch.rowCount)throw appError("Branch not found",404);const minutes=Math.min(60,Math.max(5,input.expiresInMinutes??15));const code=`LAB-${randomBytes(18).toString("base64url")}`;await query(`insert into device_activation_codes(tenant_id,branch_id,code_hash,expires_at,created_by) values($1,$2,$3,now()+($4||' minutes')::interval,$5)`,[principal.tenantId,input.branchId,secretDigest(code),minutes,principal.userId]);return {activationCode:code,expiresInMinutes:minutes};}

export async function activateDevice(input:{activationCode:string;deviceId:string;deviceSecret:string;installationId:string;deviceName:string;username:string;password:string}){
  const result=await transaction(async client=>{const activation=(await client.query<{id:string;tenant_id:string;branch_id:string}>(`select id,tenant_id,branch_id from device_activation_codes where code_hash=$1 and used_at is null and expires_at>now() for update`,[secretDigest(input.activationCode)])).rows[0];if(!activation)throw appError("Activation code is invalid or expired",401);
    const user=(await client.query<{id:string;username:string;display_name:string;password_hash:string;auth_epoch:number}>(`select u.id,u.username,u.display_name,u.password_hash,u.auth_epoch from users u join user_branches ub on ub.tenant_id=u.tenant_id and ub.user_id=u.id and ub.branch_id=$2 and ub.is_active where u.tenant_id=$1 and u.username=lower($3) and u.is_active`,[activation.tenant_id,activation.branch_id,input.username.trim()])).rows[0];if(!user||!verifyPassword(input.password,user.password_hash))throw appError("Online user verification failed",401);
    const existing=await client.query(`select 1 from devices where tenant_id=$1 and branch_id=$2 and status='ACTIVE'`,[activation.tenant_id,activation.branch_id]);if(existing.rowCount)throw appError("This branch already has an active billing device",409);
    const device=(await client.query<DeviceRow>(`insert into devices(id,tenant_id,branch_id,name,installation_id,secret_hash) values($1,$2,$3,$4,$5,$6) returning *`,[input.deviceId,activation.tenant_id,activation.branch_id,safeText(input.deviceName,"device name",100),input.installationId,secretDigest(input.deviceSecret)])).rows[0];await client.query(`update device_activation_codes set used_at=now(),used_by_device_id=$2 where id=$1`,[activation.id,device.id]);return {device,user};});
  const snapshot=await catalogSnapshot(result.device.tenant_id);await query(`insert into device_catalog_snapshots(tenant_id,device_id,version,catalog_json) values($1,$2,$3,$4) on conflict do nothing`,[result.device.tenant_id,result.device.id,snapshot.version,JSON.stringify(snapshot.catalog)]);const bootstrap=await getBootstrap(result.device,snapshot);const lease=await issueUserLease(result.device,result.user,snapshot.version);return {...bootstrap,lease};
}

async function getBootstrap(device:DeviceRow,snapshot?:Awaited<ReturnType<typeof catalogSnapshot>>){const catalog=snapshot??await catalogSnapshot(device.tenant_id);const [tenant,branch,patients,doctors,partners,users]=await Promise.all([
  query(`select id,code,name,address,phone,timezone,currency_code,receipt_footer,receipt_format,logo_url,offline_max_bill_minor::text,counter_discount_limit_bps,admin_discount_limit_bps from tenants where id=$1`,[device.tenant_id]),
  query(`select id,code,name,address,phone,coalesce(timezone,(select timezone from tenants where id=$1)) timezone from branches where tenant_id=$1 and id=$2`,[device.tenant_id,device.branch_id]),
  query(`select id,patient_number,full_name,sex,mobile,is_active,updated_at from patients where tenant_id=$1 and registration_branch_id=$2`,[device.tenant_id,device.branch_id]),
  query(`select id,code,name,phone,is_active from doctors where tenant_id=$1 and (branch_id is null or branch_id=$2)`,[device.tenant_id,device.branch_id]),
  query(`select id,code,name,type,is_active from referral_partners where tenant_id=$1 and (branch_id is null or branch_id=$2)`,[device.tenant_id,device.branch_id]),
  query(`select u.id,u.username,u.display_name,u.auth_epoch,u.is_active from users u join user_branches ub on ub.tenant_id=u.tenant_id and ub.user_id=u.id and ub.branch_id=$2 and ub.is_active where u.tenant_id=$1`,[device.tenant_id,device.branch_id]),
]);return {contractVersion:1,device:{id:device.id,tenantId:device.tenant_id,branchId:device.branch_id,epoch:device.authorization_epoch},tenant:tenant.rows[0],branch:branch.rows[0],patients:patients.rows,doctors:doctors.rows,partners:partners.rows,users:users.rows,catalogVersion:catalog.version,catalog:catalog.catalog,leasePublicKeyPem:signingPublicKey(),serverTime:new Date().toISOString()};}

export async function authenticateDevice(deviceId:string,deviceSecret:string,installationId:string,requireActive=true):Promise<DeviceContext>{const device=(await query<DeviceRow>(`select * from devices where id=$1`,[deviceId])).rows[0];if(!device||device.secret_hash!==secretDigest(deviceSecret)||device.installation_id!==installationId)throw appError("Invalid device credentials",401);if(requireActive&&device.status!=="ACTIVE")throw appError(`Device is ${device.status.toLowerCase()}`,403);await query(`update devices set last_seen_at=now() where id=$1`,[device.id]);return {device};}

export async function refreshOfflineUser(context:DeviceContext,input:{username:string;password:string}){if(context.device.status!=="ACTIVE")throw appError("Device is not active",403);const user=(await query<{id:string;username:string;display_name:string;password_hash:string;auth_epoch:number}>(`select u.id,u.username,u.display_name,u.password_hash,u.auth_epoch from users u join user_branches ub on ub.tenant_id=u.tenant_id and ub.user_id=u.id and ub.branch_id=$2 and ub.is_active where u.tenant_id=$1 and u.username=lower($3) and u.is_active`,[context.device.tenant_id,context.device.branch_id,input.username.trim()])).rows[0];if(!user||!verifyPassword(input.password,user.password_hash))throw appError("Online user verification failed",401);const snapshot=await catalogSnapshot(context.device.tenant_id);await query(`insert into device_catalog_snapshots(tenant_id,device_id,version,catalog_json) values($1,$2,$3,$4) on conflict do nothing`,[context.device.tenant_id,context.device.id,snapshot.version,JSON.stringify(snapshot.catalog)]);return {bootstrap:await getBootstrap(context.device,snapshot),lease:await issueUserLease(context.device,user,snapshot.version)};}

async function validateEnvelope(context:DeviceContext,envelope:SyncEnvelope){if(envelope.contractVersion!==1)throw appError("Unsupported sync contract",409);if(envelope.deviceId!==context.device.id||envelope.tenantId!==context.device.tenant_id||envelope.branchId!==context.device.branch_id)throw appError("Sync scope does not match authenticated device",403);const claims=verifyLease(envelope.leaseToken);if(claims.deviceId!==context.device.id||claims.tenantId!==context.device.tenant_id||claims.branchId!==context.device.branch_id||claims.userId!==envelope.actorUserId||claims.deviceEpoch!==context.device.authorization_epoch)throw appError("Lease scope does not match operation",403);const occurred=Date.parse(envelope.occurredAtUtc);if(!Number.isFinite(occurred)||occurred<Date.parse(claims.issuedAt)-300000||occurred>Date.parse(claims.expiresAt))throw appError("Operation was not created within its authorization lease",403);const user=(await query<{id:string;username:string;display_name:string;auth_epoch:number;is_active:boolean}>(`select id,username,display_name,auth_epoch,is_active from users where tenant_id=$1 and id=$2`,[claims.tenantId,claims.userId])).rows[0];if(!user?.is_active)throw appError("Operation actor is no longer active",409);const auth=await authorizationVersion(claims.tenantId,claims.userId,user.auth_epoch);if(auth.version!==claims.authorizationVersion)throw appError("Authorization changed after this operation was queued",409);return {claims,user,principal:{sessionId:`device:${context.device.id}`,tenantId:claims.tenantId,branchId:claims.branchId,userId:claims.userId,username:user.username,displayName:user.display_name,forcePasswordChange:false,permissions:new Set(auth.permissions)} satisfies SessionPrincipal};}

async function completeInbox(tenantId:string,operationId:string,status:"ACKNOWLEDGED"|"CONFLICTED"|"QUARANTINED",response:Record<string,unknown>){await query(`update device_sync_inbox set status=$3,response_json=$4,completed_at=now() where tenant_id=$1 and operation_id=$2`,[tenantId,operationId,status,JSON.stringify(response)]);return response;}

export async function syncPush(context:DeviceContext,envelopes:SyncEnvelope[]){const acknowledgements=[] as Record<string,unknown>[];for(const envelope of envelopes){const hash=requestHash(envelope);const inserted=await query(`insert into device_sync_inbox(tenant_id,branch_id,device_id,operation_id,operation_type,contract_version,payload_hash,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict do nothing`,[context.device.tenant_id,context.device.branch_id,context.device.id,envelope.operationId,envelope.operationType,envelope.contractVersion,hash,envelope.occurredAtUtc]);const existing=(await query<{payload_hash:string;response_json:Record<string,unknown>|null;status:string}>(`select payload_hash,response_json,status from device_sync_inbox where tenant_id=$1 and operation_id=$2`,[context.device.tenant_id,envelope.operationId])).rows[0];if(!inserted.rowCount&&existing.payload_hash!==hash){acknowledgements.push({operationId:envelope.operationId,status:"CONFLICTED",error:"Operation identity was reused with different content"});continue;}if(existing.response_json){acknowledgements.push({...existing.response_json,replayed:true});continue;}if(context.device.status!=="ACTIVE"){acknowledgements.push(await completeInbox(context.device.tenant_id,envelope.operationId,"QUARANTINED",{operationId:envelope.operationId,status:"QUARANTINED",error:`Device was ${context.device.status.toLowerCase()} before upload; evidence retained for review`}));continue;}
    try{const validated=await validateEnvelope(context,envelope);let outcome:Record<string,unknown>;
      if(envelope.operationType==="CREATE_PATIENT"){if(!validated.claims.permissions.includes(permissionKey("patients","create")))throw appError("Offline lease does not allow patient creation",403);const p=envelope.payload;const id=safeText(p.id,"patient identity",80);const patientNumber=safeText(p.patientNumber,"patient number",80);const fullName=safeText(p.fullName,"patient name",200);const sex=String(p.sex??"UNKNOWN");if(!["M","F","OTHER","UNKNOWN"].includes(sex))throw new Error("Invalid patient sex");await query(`insert into patients(id,tenant_id,registration_branch_id,patient_number,full_name,sex,mobile,mobile_normalized) values($1,$2,$3,upper($4),$5,$6,$7,$8) on conflict(tenant_id,id) do nothing`,[id,context.device.tenant_id,context.device.branch_id,patientNumber,fullName,sex,String(p.mobile??"")||null,normalizePhone(p.mobile)]);const row=(await query<{patient_number:string;full_name:string}>(`select patient_number,full_name from patients where tenant_id=$1 and id=$2`,[context.device.tenant_id,id])).rows[0];if(!row||row.patient_number!==patientNumber.toUpperCase()||row.full_name!==fullName)throw appError("Patient identity conflicts with an existing record",409);outcome={patientId:id};}
      else if(envelope.operationType==="POST_BILL"){if(!validated.claims.permissions.includes(permissionKey("billing","create")))throw appError("Offline lease does not allow billing",403);const input=envelope.payload as unknown as BillInput;if(input.catalogVersion!==validated.claims.catalogVersion)throw appError("Bill catalog version does not match its lease",409);const response=await postBill(validated.principal,{...input,operationId:envelope.operationId,originDeviceId:context.device.id});outcome={...response,localReceiptNumber:input.localReceiptNumber};}
      else {const permission=envelope.operationType==="REQUEST_REFUND"?permissionKey("refund","create"):permissionKey("billing_adjustment","create");if(!validated.claims.permissions.includes(permission))throw appError("Offline lease does not allow this request",403);const p=envelope.payload;const bill=(await query<{id:string}>(`select id from bills where tenant_id=$1 and origin_device_id=$2 and operation_id=$3`,[context.device.tenant_id,context.device.id,safeText(p.billOperationId,"bill operation identity",160)])).rows[0];if(!bill)throw appError("The bill must synchronize before an online-only request can be captured",409);const amount=envelope.operationType==="REQUEST_REFUND"?requireNonNegativeMoney(String(p.amount??"0"),"Requested refund"):null;const row=(await query<{id:string}>(`insert into offline_action_requests(tenant_id,branch_id,device_id,operation_id,bill_id,local_bill_operation_id,request_type,amount_minor,reason,requested_by,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) on conflict(tenant_id,operation_id) do update set operation_id=excluded.operation_id returning id`,[context.device.tenant_id,context.device.branch_id,context.device.id,envelope.operationId,bill.id,p.billOperationId,envelope.operationType==="REQUEST_REFUND"?"REFUND":"CANCELLATION",amount,safeText(p.reason,"request reason",500),validated.principal.userId,envelope.occurredAtUtc])).rows[0];outcome={requestId:row.id,cloudBillId:bill.id,status:"CAPTURED_FOR_ONLINE_REVIEW"};}
      const ack={operationId:envelope.operationId,status:"ACKNOWLEDGED",outcome};await query(`insert into device_sync_events(tenant_id,branch_id,device_id,entity_type,entity_id,payload) values($1,$2,$3,$4,$5,$6)`,[context.device.tenant_id,context.device.branch_id,context.device.id,envelope.operationType,envelope.operationId,JSON.stringify(ack)]);acknowledgements.push(await completeInbox(context.device.tenant_id,envelope.operationId,"ACKNOWLEDGED",ack));
    }catch(error){const message=error instanceof Error?error.message:"Sync failed";acknowledgements.push(await completeInbox(context.device.tenant_id,envelope.operationId,"QUARANTINED",{operationId:envelope.operationId,status:"QUARANTINED",error:message}));}}
  return {acknowledgements,serverTime:new Date().toISOString()};}

export async function syncPull(context:DeviceContext,after:number){if(context.device.status!=="ACTIVE")throw appError("Device is not active",403);const rows=(await query<{sequence_id:string;payload:Record<string,unknown>}>(`select sequence_id::text,payload from device_sync_events where tenant_id=$1 and device_id=$2 and sequence_id>$3 order by sequence_id limit 500`,[context.device.tenant_id,context.device.id,after])).rows;return {events:rows.map(row=>({sequence:Number(row.sequence_id),...row.payload})),checkpoint:rows.length?Number(rows.at(-1)!.sequence_id):after,serverTime:new Date().toISOString()};}

export async function onlineDueCollection(context:DeviceContext,input:{leaseToken:string;billOperationId:string;operationId:string;amount:string;method:"CASH"|"BKASH"|"NAGAD"|"CARD"|"BANK";reference?:string}){const claims=verifyLease(input.leaseToken);const envelope={contractVersion:1 as const,operationId:input.operationId,operationType:"POST_BILL" as const,tenantId:context.device.tenant_id,branchId:context.device.branch_id,deviceId:context.device.id,actorUserId:claims.userId,occurredAtUtc:new Date().toISOString(),businessDate:new Date().toISOString().slice(0,10),leaseToken:input.leaseToken,dependencies:[],payload:{}};const validated=await validateEnvelope(context,envelope);const bill=(await query<{id:string}>(`select id from bills where tenant_id=$1 and origin_device_id=$2 and operation_id=$3`,[context.device.tenant_id,context.device.id,input.billOperationId])).rows[0];if(!bill)throw appError("Bill is not confirmed by the cloud",409);const result=await collectDue(validated.principal,{operationId:input.operationId,billId:bill.id,amount:input.amount,method:input.method,reference:input.reference});const event={operationId:input.operationId,status:"CLOUD_DUE_COLLECTION_CONFIRMED",billOperationId:input.billOperationId,outcome:result};await query(`insert into device_sync_events(tenant_id,branch_id,device_id,entity_type,entity_id,payload) values($1,$2,$3,'DUE_COLLECTION',$4,$5)`,[context.device.tenant_id,context.device.branch_id,context.device.id,input.operationId,JSON.stringify(event)]);return event;}

export async function setDeviceStatus(principal:SessionPrincipal,deviceId:string,status:"ACTIVE"|"DISABLED"|"REVOKED"){assertPermission(principal,"devices","update");if(status==="ACTIVE")throw new Error("Reactivation requires a new controlled activation");const row=await query(`update devices set status=$3,authorization_epoch=authorization_epoch+1,disabled_at=case when $3='DISABLED' then now() else disabled_at end,revoked_at=case when $3='REVOKED' then now() else revoked_at end where tenant_id=$1 and id=$2 returning id`,[principal.tenantId,deviceId,status]);if(!row.rowCount)throw appError("Device not found",404);return {deviceId,status};}

export async function listDevices(tenantId:string){return (await query(`select d.id,d.name,d.status,d.activated_at,d.last_seen_at,b.code branch_code,b.name branch_name from devices d join branches b on b.tenant_id=d.tenant_id and b.id=d.branch_id where d.tenant_id=$1 order by d.activated_at desc`,[tenantId])).rows;}
