export const ENCOUNTER_ERROR_CODES = {
  ENCOUNTER_NOT_FOUND: "ENCOUNTER_NOT_FOUND",
  ENCOUNTER_ALREADY_STARTED: "ENCOUNTER_ALREADY_STARTED",
  ENCOUNTER_ALREADY_COMPLETED: "ENCOUNTER_ALREADY_COMPLETED",
  ENCOUNTER_STATUS_INVALID: "ENCOUNTER_STATUS_INVALID",
  ENCOUNTER_NOT_EDITABLE: "ENCOUNTER_NOT_EDITABLE",
  ENCOUNTER_VALIDATION: "ENCOUNTER_VALIDATION",
  ENCOUNTER_BRANCH_INACTIVE: "ENCOUNTER_BRANCH_INACTIVE",
  ENCOUNTER_BRANCH_UNAUTHORIZED: "ENCOUNTER_BRANCH_UNAUTHORIZED",
  ENCOUNTER_DOCTOR_INACTIVE: "ENCOUNTER_DOCTOR_INACTIVE",
  ENCOUNTER_DOCTOR_BRANCH: "ENCOUNTER_DOCTOR_BRANCH",
  ENCOUNTER_PATIENT_INACTIVE: "ENCOUNTER_PATIENT_INACTIVE",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  APPOINTMENT_NOT_READY: "APPOINTMENT_NOT_READY",
  APPOINTMENT_WRONG_DOCTOR: "APPOINTMENT_WRONG_DOCTOR",
  APPOINTMENT_WRONG_BRANCH: "APPOINTMENT_WRONG_BRANCH",
  APPOINTMENT_INVALID_STATUS: "APPOINTMENT_INVALID_STATUS",
  VITALS_INVALID: "VITALS_INVALID",
  REOPEN_REASON_REQUIRED: "REOPEN_REASON_REQUIRED",
  REOPEN_DENIED: "REOPEN_DENIED",
  PRINT_DENIED: "PRINT_DENIED",
} as const;

export type EncounterErrorCode =
  (typeof ENCOUNTER_ERROR_CODES)[keyof typeof ENCOUNTER_ERROR_CODES];
