export type PermissionAction =
  | "canView"
  | "canCreate"
  | "canEdit"
  | "canDelete"
  | "canApprove"
  | "canPrint";

export type PermissionResource = {
  resourceKey: string;
  moduleCode: string;
  permissionCode: string;
  label: string;
  route: string;
  group: string;
};

export const PERMISSION_ACTIONS: Array<{
  key: PermissionAction;
  label: string;
}> = [
  { key: "canView", label: "View" },
  { key: "canCreate", label: "Create" },
  { key: "canEdit", label: "Edit" },
  { key: "canDelete", label: "Delete" },
  { key: "canApprove", label: "Approve" },
  { key: "canPrint", label: "Print" },
];

export const TENANT_PERMISSION_RESOURCES: PermissionResource[] = [
  {
    resourceKey: "/settings/users",
    moduleCode: "MOD-02",
    permissionCode: "USER_MGMT",
    label: "User Management",
    route: "/settings/users",
    group: "Security & IAM",
  },
  {
    resourceKey: "/settings/roles",
    moduleCode: "MOD-03",
    permissionCode: "ROLE_MGMT",
    label: "Roles & Permissions",
    route: "/settings/roles",
    group: "Security & IAM",
  },
  {
    resourceKey: "/settings/audit",
    moduleCode: "MOD-04",
    permissionCode: "AUDIT_CENTER",
    label: "Audit Center",
    route: "/settings/audit",
    group: "Security & IAM",
  },
  {
    resourceKey: "/settings/branches",
    moduleCode: "MOD-07",
    permissionCode: "BRANCH_MGMT",
    label: "Branch Management",
    route: "/settings/branches",
    group: "Security & IAM",
  },
  {
    resourceKey: "/settings/service-catalog",
    moduleCode: "MOD-10",
    permissionCode: "SERVICE_CATALOG",
    label: "Service Catalog Import",
    route: "/settings/service-catalog",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/services",
    moduleCode: "MOD-10",
    permissionCode: "IMPORTED_SERVICES",
    label: "Imported Services",
    route: "/settings/services",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/test-parameters",
    moduleCode: "MOD-22",
    permissionCode: "TEST_PARAMETERS",
    label: "Test Parameters",
    route: "/settings/test-parameters",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/sample-types",
    moduleCode: "MOD-21",
    permissionCode: "SAMPLE_TYPES",
    label: "Sample Types",
    route: "/settings/sample-types",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/containers",
    moduleCode: "MOD-21",
    permissionCode: "CONTAINERS",
    label: "Containers & Tubes",
    route: "/settings/containers",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/analyzers",
    moduleCode: "MOD-22",
    permissionCode: "ANALYZERS",
    label: "Analyzers",
    route: "/settings/analyzers",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/doctors",
    moduleCode: "MOD-11",
    permissionCode: "DOCTORS",
    label: "Doctors",
    route: "/settings/doctors",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/settings/report-layouts",
    moduleCode: "MOD-24",
    permissionCode: "REPORT_LAYOUTS",
    label: "Report Layouts",
    route: "/settings/report-layouts",
    group: "Diagnostic Setup",
  },
  {
    resourceKey: "/dashboard",
    moduleCode: "MOD-15",
    permissionCode: "DASHBOARD",
    label: "Diagnostic Dashboard",
    route: "/dashboard",
    group: "Operations",
  },
  {
    resourceKey: "/patients",
    moduleCode: "MOD-15",
    permissionCode: "PATIENT_SEARCH",
    label: "Patient Search",
    route: "/patients",
    group: "Operations",
  },
  {
    resourceKey: "/patients/new",
    moduleCode: "MOD-15",
    permissionCode: "PATIENT_REGISTER",
    label: "Patient Registration",
    route: "/patients/new",
    group: "Operations",
  },
  {
    resourceKey: "/prescriptions/revise",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_REVISE",
    label: "Revise Prescription",
    route: "/prescriptions/revise",
    group: "Clinical",
  },
  {
    resourceKey: "/prescriptions/cancel",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_CANCEL",
    label: "Cancel Prescription",
    route: "/prescriptions/cancel",
    group: "Clinical",
  },
  {
    resourceKey: "/prescriptions/finalize",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_FINALIZE",
    label: "Finalize Prescription",
    route: "/prescriptions/finalize",
    group: "Clinical",
  },
  {
    resourceKey: "/prescriptions/print",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_PRINT",
    label: "Print Prescription",
    route: "/prescriptions/print",
    group: "Clinical",
  },
  {
    resourceKey: "/prescriptions/edit",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_EDIT",
    label: "Edit Prescription",
    route: "/prescriptions/edit",
    group: "Clinical",
  },
  {
    resourceKey: "/prescriptions/new",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_CREATE",
    label: "Create Prescription",
    route: "/prescriptions/new",
    group: "Clinical",
  },
  {
    resourceKey: "/prescriptions/history",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_HISTORY",
    label: "Prescription History",
    route: "/prescriptions/history",
    group: "Clinical",
  },
  {

    resourceKey: "/prescriptions",
    moduleCode: "MOD-19",
    permissionCode: "PRESCRIPTION_MGMT",
    label: "Prescriptions",
    route: "/prescriptions",
    group: "Clinical",
  },
  {
    resourceKey: "/pharmacy/medications/search",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_SEARCH",
    label: "Medication Search",
    route: "/pharmacy/medications/search",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/medications",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_CATALOG_VIEW",
    label: "Medication Catalog",
    route: "/pharmacy/medications",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/medications/new",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_CATALOG_CREATE",
    label: "Create Medication",
    route: "/pharmacy/medications/new",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/medications/edit",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_CATALOG_EDIT",
    label: "Edit Medication",
    route: "/pharmacy/medications/edit",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/generics",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_GENERIC_MANAGE",
    label: "Generic Master",
    route: "/pharmacy/generics",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/manufacturers",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_MANUFACTURER_MANAGE",
    label: "Manufacturer Master",
    route: "/pharmacy/manufacturers",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/reference-data",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_REFERENCE_MANAGE",
    label: "Medication Reference Data",
    route: "/pharmacy/reference-data",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/branch-availability",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_BRANCH_AVAILABILITY",
    label: "Branch Medication Availability",
    route: "/pharmacy/branch-availability",
    group: "Pharmacy",
  },
  {
    resourceKey: "/pharmacy/import",
    moduleCode: "MOD-20",
    permissionCode: "MEDICATION_CATALOG_IMPORT",
    label: "Medication Import",
    route: "/pharmacy/import",
    group: "Pharmacy",
  },
  {
    resourceKey: "/consultations/reopen",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_REOPEN",
    label: "Reopen Consultation",
    route: "/consultations/reopen",
    group: "Clinical",
  },
  {
    resourceKey: "/consultations/print",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_PRINT",
    label: "Print Consultation",
    route: "/consultations/print",
    group: "Clinical",
  },
  {
    resourceKey: "/consultations/complete",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_COMPLETE",
    label: "Complete Consultation",
    route: "/consultations/complete",
    group: "Clinical",
  },
  {
    resourceKey: "/consultations/vitals",
    moduleCode: "MOD-18",
    permissionCode: "VITALS_CAPTURE",
    label: "Capture Vitals",
    route: "/consultations/vitals",
    group: "Clinical",
  },
  {
    resourceKey: "/consultations/edit",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_EDIT",
    label: "Edit Consultation",
    route: "/consultations/edit",
    group: "Clinical",
  },
  {
    resourceKey: "/consultations/start",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_START",
    label: "Start Consultation",
    route: "/consultations/start",
    group: "Clinical",
  },
  {
    resourceKey: "/doctor/worklist",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_WORKLIST",
    label: "Doctor Worklist",
    route: "/doctor/worklist",
    group: "Clinical",
  },
  {
    resourceKey: "/consultations",
    moduleCode: "MOD-18",
    permissionCode: "CONSULTATION_MGMT",
    label: "Consultations",
    route: "/consultations",
    group: "Clinical",
  },
  {
    resourceKey: "/appointments/queue/operator",
    moduleCode: "MOD-17",
    permissionCode: "QUEUE_OPERATE",
    label: "Queue Operator",
    route: "/appointments/queue/operator",
    group: "Operations",
  },
  {
    resourceKey: "/appointments/queue",
    moduleCode: "MOD-17",
    permissionCode: "QUEUE_MGMT",
    label: "Queue Dashboard",
    route: "/appointments/queue",
    group: "Operations",
  },
  {
    resourceKey: "/appointments/new",
    moduleCode: "MOD-17",
    permissionCode: "APPOINTMENT_BOOK",
    label: "Appointment Booking",
    route: "/appointments/new",
    group: "Operations",
  },
  {
    resourceKey: "/appointments",
    moduleCode: "MOD-17",
    permissionCode: "APPOINTMENT_MGMT",
    label: "Appointment List",
    route: "/appointments",
    group: "Operations",
  },
  {
    resourceKey: "/diagnostic/billing",
    moduleCode: "MOD-10",
    permissionCode: "DIAG_BILLING",
    label: "Diagnostic Billing",
    route: "/diagnostic/billing",
    group: "Operations",
  },
  {
    resourceKey: "/lab/orders",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDERS",
    label: "Lab Orders",
    route: "/lab/orders",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/orders/new",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDER_CREATE",
    label: "Create Lab Order",
    route: "/lab/orders/new",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/orders/edit",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDER_EDIT",
    label: "Edit Lab Order",
    route: "/lab/orders/edit",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/orders/confirm",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDER_CONFIRM",
    label: "Confirm Lab Order",
    route: "/lab/orders/confirm",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/orders/manual",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDER_MANUAL",
    label: "Manual Lab Order",
    route: "/lab/orders/manual",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/orders/collect",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDER_COLLECT",
    label: "Collect Lab Sample",
    route: "/lab/orders/collect",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/collection",
    moduleCode: "MOD-21",
    permissionCode: "LAB_COLLECTION_WORKLIST",
    label: "Collection Worklist",
    route: "/lab/collection",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/receipt",
    moduleCode: "MOD-21",
    permissionCode: "LAB_RECEIPT",
    label: "Sample Receipt",
    route: "/lab/receipt",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/processing",
    moduleCode: "MOD-21",
    permissionCode: "LAB_PROCESSING",
    label: "Sample Processing",
    route: "/lab/processing",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/samples/label",
    moduleCode: "MOD-21",
    permissionCode: "LAB_SAMPLE_LABEL",
    label: "Sample Label Print",
    route: "/lab/samples/label",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/orders/cancel",
    moduleCode: "MOD-21",
    permissionCode: "LAB_ORDER_CANCEL",
    label: "Cancel Lab Order",
    route: "/lab/orders/cancel",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/sample-collection",
    moduleCode: "MOD-21",
    permissionCode: "SAMPLE_COLLECTION",
    label: "Sample Collection",
    route: "/lab/sample-collection",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/label-print",
    moduleCode: "MOD-21",
    permissionCode: "LABEL_PRINT",
    label: "Label Print",
    route: "/lab/label-print",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/lis-worklist",
    moduleCode: "MOD-22",
    permissionCode: "LIS_WORKLIST",
    label: "LIS Worklist",
    route: "/lab/lis-worklist",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/result-entry",
    moduleCode: "MOD-22",
    permissionCode: "RESULT_ENTRY",
    label: "Manual Result Entry",
    route: "/lab/result-entry",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/result-entry/edit",
    moduleCode: "MOD-22",
    permissionCode: "RESULT_ENTRY_EDIT",
    label: "Edit Result Entry",
    route: "/lab/result-entry/edit",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/result-entry/complete",
    moduleCode: "MOD-22",
    permissionCode: "RESULT_ENTRY_COMPLETE",
    label: "Complete Result Entry",
    route: "/lab/result-entry/complete",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/result-entry/reopen",
    moduleCode: "MOD-22",
    permissionCode: "RESULT_ENTRY_REOPEN",
    label: "Reopen Result Entry",
    route: "/lab/result-entry/reopen",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/result-entry/critical-acknowledge",
    moduleCode: "MOD-22",
    permissionCode: "RESULT_CRITICAL_ACK",
    label: "Acknowledge Critical Value",
    route: "/lab/result-entry/critical-acknowledge",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/verification",
    moduleCode: "MOD-23",
    permissionCode: "VERIFICATION",
    label: "Result Verification",
    route: "/lab/verification",
    group: "Laboratory",
  },
  {
    resourceKey: "/lab/report-release",
    moduleCode: "MOD-24",
    permissionCode: "REPORT_RELEASE",
    label: "Report Release",
    route: "/lab/report-release",
    group: "Laboratory",
  },
  {
    resourceKey: "/portal/reports",
    moduleCode: "MOD-30",
    permissionCode: "PORTAL_REPORTS",
    label: "Patient Portal Reports",
    route: "/portal/reports",
    group: "Portal",
  },
];

export function getResourceByRoute(route: string): PermissionResource | undefined {
  const normalized = route.split("?")[0]?.replace(/\/$/, "") || "/";
  return TENANT_PERMISSION_RESOURCES.find(
    (resource) =>
      resource.route === normalized ||
      normalized.startsWith(`${resource.route}/`),
  );
}

export function getResourceGroups(): string[] {
  return [...new Set(TENANT_PERMISSION_RESOURCES.map((resource) => resource.group))];
}
