import { requirePrincipal } from "../../../lib/session";
import { listTenantTests } from "../../../services/catalog";
import { query } from "../../../lib/db";
import { addReferenceRangeAction, createCatalogLookupAction, installCatalogAction, installCatalogTierAction, updateResultFieldAction, updateTenantTestAction } from "../../actions";
export default async function CatalogPage() {
  const p = await requirePrincipal("catalog", "read");
  const [tests, templates, fields] = await Promise.all([listTenantTests(p.tenantId), query<{ code:string;name:string;review_status:string;min_tier:string|null;release_code:string|null }>(`select code,name,review_status,min_tier,release_code from catalog_templates where is_active order by code`), query<{id:string;test_code:string;code:string;name:string;result_type:string;method_code:string|null}>(`select f.id,t.code test_code,f.code,f.name,f.result_type,f.method_code from tenant_result_fields f join tenant_tests t on t.tenant_id=f.tenant_id and t.id=f.tenant_test_id where f.tenant_id=$1 and f.is_active order by t.code,f.display_order`,[p.tenantId])]);
  return <main><h1>Test catalog</h1><section className="card warning">Templates are global, versioned master data. Draft templates install disabled for local clinical configuration. Tenant prices, activation state, and marked customizations are never overwritten during refresh.</section>
    <section className="card"><h2>Install master tier</h2><form className="stack" action={installCatalogTierAction}><label>Cumulative tier<select name="tier"><option value="STARTER">Starter (312)</option><option value="MEDIUM">Medium (444)</option><option value="ADVANCED">Advanced (725)</option></select></label><button>Install / refresh tier as disabled</button></form></section>
    <section className="card"><h2>Install one template</h2><form className="stack" action={installCatalogAction}><label>Template<select name="templateCode">{templates.rows.map(t=><option key={t.code} value={t.code}>{t.code} — {t.name} ({t.min_tier??"LOCAL"}; {t.review_status}; {t.release_code??"unversioned"})</option>)}</select></label><label>Tenant price (leave blank while unconfigured)<input name="price" inputMode="decimal" /></label><button>Install / refresh</button></form></section>
    <section className="card"><h2>Tenant tests</h2>{tests.map(t=><form className="grid" key={t.id} action={updateTenantTestAction}><input type="hidden" name="testId" value={t.id}/><label>Code<input value={t.code} readOnly/></label><label>Name<input name="name" defaultValue={t.name}/></label><label>Price<input name="price" defaultValue={t.price??""}/></label><label>Review<input value={t.review_status} readOnly/></label><label>Activation<input value={t.is_active?"ACTIVE":"DISABLED"} readOnly/></label><button>Save tenant values</button></form>)}</section>
    <section className="card"><h2>Groups, specimens, and units</h2><form className="grid" action={createCatalogLookupAction}><label>Type<select name="kind"><option value="group">Group</option><option value="specimen">Specimen</option><option value="unit">Unit</option></select></label><label>Code<input name="code" required/></label><label>Name<input name="name" required/></label><label>Container / symbol<input name="detail"/></label><button>Add lookup</button></form></section>
    <section className="card"><h2>Result fields and custom reference ranges</h2>{fields.rows.map(f=><div key={f.id}><form className="grid" action={updateResultFieldAction}><input type="hidden" name="fieldId" value={f.id}/><label>Field<input value={`${f.test_code} / ${f.code} / ${f.result_type}`} readOnly/></label><label>Name<input name="name" defaultValue={f.name}/></label><label>Method<input name="methodCode" defaultValue={f.method_code??""}/></label><button>Mark customized</button></form><form className="grid" action={addReferenceRangeAction}><input type="hidden" name="fieldId" value={f.id}/><label>Sex<select name="sex"><option value="">Any</option><option>M</option><option>F</option><option>OTHER</option></select></label><label>Age from days<input name="ageFrom" type="number" min="0"/></label><label>Age to days<input name="ageTo" type="number" min="0"/></label><label>Low<input name="low" inputMode="decimal"/></label><label>High<input name="high" inputMode="decimal"/></label><label>Text range<input name="textRange"/></label><label>Method<input name="methodCode"/></label><button>Add unreviewed range</button></form><hr/></div>)}</section></main>;
}
