import { app,BrowserWindow,dialog,ipcMain,safeStorage,session } from "electron";
import { randomBytes,randomUUID } from "node:crypto";
import { copyFileSync,existsSync,readFileSync,writeFileSync,mkdirSync,renameSync,rmSync } from "node:fs";
import path from "node:path";
import { LocalStore } from "./local-store";
import { SyncClient,type DeviceConfig } from "./sync-client";
import { OperationalLogger } from "./operational-log";
import type { Bootstrap,LocalSession,OfflineBillInput } from "../shared/contracts";

const gotLock=app.requestSingleInstanceLock();if(!gotLock)app.quit();
if(process.env.LAB_LITE_USER_DATA_DIR)app.setPath("userData",path.resolve(process.env.LAB_LITE_USER_DATA_DIR));
let win:BrowserWindow|undefined,store:LocalStore|undefined,syncClient:SyncClient|undefined,currentSession:LocalSession|undefined,logger:OperationalLogger|undefined;
const paths=()=>{const root=app.getPath("userData");return {root,db:path.join(root,"lab-lite.db"),key:path.join(root,"database-key.dpapi"),secret:path.join(root,"device-secret.dpapi"),config:path.join(root,"device.json"),receipts:path.join(root,"receipts"),backups:path.join(root,"backups"),logs:path.join(root,"logs")};};
const log=(event:string,fields:Record<string,string|number|boolean|null>={})=>logger?.write(event,fields);
function encryptedWrite(file:string,value:string){if(!safeStorage.isEncryptionAvailable())throw new Error("Windows protected storage is unavailable");writeFileSync(file,safeStorage.encryptString(value),{mode:0o600});}
function encryptedRead(file:string){return safeStorage.decryptString(readFileSync(file));}
function openActivated(){const p=paths();if(!existsSync(p.config)||!existsSync(p.key)||!existsSync(p.db))return;const config=JSON.parse(readFileSync(p.config,"utf8")) as DeviceConfig;try{store=new LocalStore(p.db,encryptedRead(p.key));syncClient=new SyncClient(store,config,encryptedRead(p.secret),log);log("local_db_open",{result:"success",checkpoint:store.state().checkpoint});}catch(error){log("local_db_open",{result:"failed",category:"encrypted_database_open"});throw error;}}
function requireStore(){if(!store)throw new Error("Device is not activated");return store;}
function requireSession(){if(!currentSession)throw new Error("Offline login is required");return currentSession;}
async function activate(input:{cloudUrl:string;activationCode:string;deviceName:string;username:string;password:string}){if(store)throw new Error("This installation is already activated");const cloudUrl=new URL(input.cloudUrl);if(cloudUrl.protocol!=="https:"&&!(["127.0.0.1","localhost"].includes(cloudUrl.hostname)&&cloudUrl.protocol==="http:"))throw new Error("Cloud URL must use HTTPS");const p=paths();mkdirSync(p.root,{recursive:true});const key=randomBytes(32).toString("base64url"),deviceSecret=randomBytes(32).toString("base64url"),config:DeviceConfig={cloudUrl:cloudUrl.origin,deviceId:`dev_${randomUUID().replaceAll("-","")}`,installationId:randomUUID()};try{const response=await fetch(`${config.cloudUrl}/api/device/activate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({activationCode:input.activationCode,deviceId:config.deviceId,deviceSecret,installationId:config.installationId,deviceName:input.deviceName,username:input.username,password:input.password})});const data=await response.json() as Bootstrap&{error?:string};if(!response.ok)throw new Error(data.error??"Activation failed");encryptedWrite(p.key,key);encryptedWrite(p.secret,deviceSecret);writeFileSync(p.config,JSON.stringify(config),{mode:0o600});store=new LocalStore(p.db,key);store.bootstrap(data,input.password,config.installationId);syncClient=new SyncClient(store,config,deviceSecret,log);app.setLoginItemSettings({openAtLogin:true});log("device_activation",{result:"success"});return store.state();}catch(error){log("device_activation",{result:"failed",category:"activation_failed"});throw error;}}

async function restoreBackup(){const p=paths(),active=requireStore(),expected=active.state().deviceId;if(!expected)throw new Error("Activated device identity is missing");const selected=await dialog.showOpenDialog({title:"Restore encrypted Lab Lite backup",properties:["openFile"],filters:[{name:"Encrypted database",extensions:["db"]}]});if(selected.canceled||selected.filePaths.length!==1)return null;mkdirSync(p.backups,{recursive:true});const stamp=new Date().toISOString().replaceAll(":","-").replaceAll(".","-");const staging=path.join(p.backups,`restore-staging-${stamp}.db`),safety=path.join(p.backups,`pre-restore-${stamp}.db`),displaced=path.join(p.backups,`displaced-${stamp}.db`);copyFileSync(selected.filePaths[0],staging);try{const key=encryptedRead(p.key),verified=LocalStore.verifyBackup(staging,key,expected);const confirmation=await dialog.showMessageBox({type:"warning",buttons:["Cancel","Restore verified backup"],defaultId:0,cancelId:0,title:"Confirm restore",message:"The backup passed encryption and device checks.",detail:`A safety backup will be created first. Pending ${verified.pending}; conflicted ${verified.conflicted}; checkpoint ${verified.checkpoint}.`});if(confirmation.response!==1){rmSync(staging,{force:true});return null;}const safetyResult=active.backup(safety);store?.close();store=undefined;syncClient=undefined;currentSession=undefined;renameSync(p.db,displaced);try{renameSync(staging,p.db);openActivated();const restored=requireStore().state();log("restore",{result:"success",pending:restored.pending,conflicted:restored.conflicted,checkpoint:restored.checkpoint});return {restored,safetyBackup:safetyResult.target,safetySha256:safetyResult.sha256};}catch(error){if(existsSync(p.db))renameSync(p.db,`${p.db}.failed-${stamp}`);renameSync(displaced,p.db);openActivated();log("restore",{result:"failed",category:"reopen_failed"});throw error;}}catch(error){rmSync(staging,{force:true});log("restore",{result:"failed",category:"validation_failed"});throw error;}}
function safeHandler(channel:string,handler:(input:any)=>unknown|Promise<unknown>){ipcMain.handle(channel,async(_event,input)=>{try{return {ok:true,data:await handler(input)};}catch(error){return {ok:false,error:error instanceof Error?error.message:"Operation failed"};}});}
function registerIpc(){safeHandler("state",()=>({...requireStore().state(),loggedIn:Boolean(currentSession),user:currentSession?.displayName??null}));safeHandler("activate",activate);safeHandler("login",input=>{try{currentSession=requireStore().login(String(input.username),String(input.password));log("offline_login",{result:"success"});return currentSession;}catch(error){log(error instanceof Error&&/clock rollback/i.test(error.message)?"clock_rollback_detected":"offline_login",{result:"failed",category:"authentication_failed"});throw error;}});safeHandler("logout",()=>{currentSession=undefined;return true;});safeHandler("context",()=>requireStore().context());safeHandler("save-draft",input=>requireStore().saveDraft(requireSession(),String(input.operationId),input.payload));safeHandler("delete-draft",input=>requireStore().deleteDraft(String(input.id)));safeHandler("post-bill",input=>requireStore().postBill(requireSession(),input as OfflineBillInput));safeHandler("capture-request",input=>requireStore().captureRequest(requireSession(),input));safeHandler("sync",async()=>{if(!syncClient)throw new Error("Sync is not configured");return syncClient.synchronize();});safeHandler("refresh-user",async input=>{if(!syncClient)throw new Error("Sync is not configured");const refreshed=await syncClient.refreshUser(String(input.username),String(input.password));requireStore().refreshBootstrap({...refreshed.bootstrap,lease:refreshed.lease},String(input.password));return true;});safeHandler("collect-due",async input=>{if(!syncClient)throw new Error("Sync is not configured");const result=await syncClient.collectDue(requireSession(),input);await syncClient.synchronize();return result;});safeHandler("report",input=>requireStore().report(String(input.date)));safeHandler("receipt",input=>openReceipt(String(input.billId),String(input.format??"A5"),String(input.copy??"PATIENT")));safeHandler("backup",async()=>{const result=await dialog.showSaveDialog({title:"Encrypted Lab Lite backup",defaultPath:`abs-lab-lite-${new Date().toISOString().slice(0,10)}.db`,filters:[{name:"Encrypted database",extensions:["db"]}]});if(result.canceled||!result.filePath)return null;try{const backup=requireStore().backup(result.filePath);log("backup",{result:"success"});return backup;}catch(error){log("backup",{result:"failed",category:"write_failed"});throw error;}});safeHandler("restore-backup",restoreBackup);}
function openReceipt(billId:string,format:string,copy:string){const p=paths();mkdirSync(p.receipts,{recursive:true});const target=path.join(p.receipts,`${billId}.html`);writeFileSync(target,requireStore().receiptHtml(billId,format,copy));const receipt=new BrowserWindow({width:900,height:900,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}});receipt.webContents.setWindowOpenHandler(()=>({action:"deny"}));receipt.webContents.on("will-navigate",event=>event.preventDefault());void receipt.loadFile(target);log("receipt_open",{result:"success",format});return true;}
function createWindow(){win=new BrowserWindow({width:1280,height:850,minWidth:960,minHeight:650,show:true,webPreferences:{preload:path.join(__dirname,"preload.cjs"),nodeIntegration:false,contextIsolation:true,sandbox:true,webviewTag:false}});win.webContents.setWindowOpenHandler(()=>({action:"deny"}));win.webContents.on("will-navigate",(event,url)=>{if(url!==win?.webContents.getURL())event.preventDefault();});void win.loadFile(path.join(__dirname,"renderer","index.html"));}
app.whenReady().then(()=>{const p=paths();logger=new OperationalLogger(p.logs);log("app_start",{appVersion:app.getVersion()});session.defaultSession.setPermissionRequestHandler((_wc,_permission,callback)=>callback(false));openActivated();registerIpc();createWindow();app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});});
app.on("second-instance",()=>{if(win){if(win.isMinimized())win.restore();win.focus();}});app.on("before-quit",()=>log("app_stop",{result:"normal"}));app.on("window-all-closed",()=>{store?.close();if(process.platform!=="darwin")app.quit();});
