export const LOCAL_MIGRATIONS=[{version:1,sql:`
CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE local_users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,password_salt TEXT NOT NULL,password_verifier TEXT NOT NULL,permissions_json TEXT NOT NULL,lease_token TEXT NOT NULL,lease_claims_json TEXT NOT NULL,failed_attempts INTEGER NOT NULL DEFAULT 0,locked_until TEXT,is_active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE patients(id TEXT PRIMARY KEY,patient_number TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,sex TEXT NOT NULL,mobile TEXT,is_active INTEGER NOT NULL DEFAULT 1,sync_status TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE catalog_tests(id TEXT PRIMARY KEY,code TEXT NOT NULL,name TEXT NOT NULL,group_name TEXT,price_minor INTEGER NOT NULL CHECK(price_minor>=0),is_active INTEGER NOT NULL,catalog_version TEXT NOT NULL);
CREATE TABLE doctors(id TEXT PRIMARY KEY,code TEXT NOT NULL,name TEXT NOT NULL,is_active INTEGER NOT NULL);
CREATE TABLE referral_partners(id TEXT PRIMARY KEY,code TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL,is_active INTEGER NOT NULL);
CREATE TABLE drafts(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,user_id TEXT NOT NULL,payload_json TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE bills(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,local_receipt_number TEXT NOT NULL UNIQUE,cloud_bill_id TEXT,cloud_bill_number TEXT,patient_id TEXT NOT NULL,patient_number_snapshot TEXT NOT NULL,patient_name_snapshot TEXT NOT NULL,patient_mobile_snapshot TEXT,doctor_name_snapshot TEXT,referral_partner_name_snapshot TEXT,currency_code TEXT NOT NULL,gross_minor INTEGER NOT NULL,discount_minor INTEGER NOT NULL,net_minor INTEGER NOT NULL,expected_delivery_at TEXT,status TEXT NOT NULL DEFAULT 'POSTED',posted_by TEXT NOT NULL,posted_by_name TEXT NOT NULL,posted_at TEXT NOT NULL,catalog_version TEXT NOT NULL,sync_status TEXT NOT NULL,cloud_balance_minor INTEGER);
CREATE TABLE bill_lines(id TEXT PRIMARY KEY,bill_id TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,test_id TEXT NOT NULL,line_key TEXT NOT NULL,test_code_snapshot TEXT NOT NULL,test_name_snapshot TEXT NOT NULL,group_name_snapshot TEXT,quantity INTEGER NOT NULL,unit_price_minor INTEGER NOT NULL,gross_minor INTEGER NOT NULL,discount_minor INTEGER NOT NULL,net_minor INTEGER NOT NULL,repeat_reason TEXT,UNIQUE(bill_id,line_key));
CREATE TABLE collections(id TEXT PRIMARY KEY,bill_id TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,operation_id TEXT NOT NULL UNIQUE,collection_number TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,amount_minor INTEGER NOT NULL,payment_method TEXT NOT NULL,external_reference TEXT,collected_by TEXT NOT NULL,collected_by_name TEXT NOT NULL,collected_at TEXT NOT NULL,sync_status TEXT NOT NULL);
CREATE TABLE offline_requests(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,bill_id TEXT NOT NULL REFERENCES bills(id),request_type TEXT NOT NULL,amount_minor INTEGER,reason TEXT NOT NULL,requested_by TEXT NOT NULL,requested_at TEXT NOT NULL,sync_status TEXT NOT NULL);
CREATE TABLE outbox(sequence INTEGER PRIMARY KEY AUTOINCREMENT,operation_id TEXT NOT NULL UNIQUE,operation_type TEXT NOT NULL,payload_json TEXT NOT NULL,payload_hash TEXT NOT NULL,lease_token TEXT NOT NULL,actor_user_id TEXT NOT NULL,occurred_at TEXT NOT NULL,business_date TEXT NOT NULL,dependencies_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',attempt_count INTEGER NOT NULL DEFAULT 0,next_attempt_at TEXT,last_error TEXT,ack_json TEXT);
CREATE TABLE sync_acks(operation_id TEXT PRIMARY KEY,ack_json TEXT NOT NULL,received_at TEXT NOT NULL);
CREATE INDEX outbox_pending ON outbox(status,sequence);
`}];
