import type { LocalStore } from "./local-store";
import type { LocalSession } from "../shared/contracts";

export type DeviceConfig={cloudUrl:string;deviceId:string;installationId:string};
export class SyncClient{
  constructor(private store:LocalStore,private config:DeviceConfig,private deviceSecret:string,private log:(event:string,fields?:Record<string,string|number|boolean|null>)=>void=()=>{}){}
  private headers(){return {"content-type":"application/json","x-device-id":this.config.deviceId,"x-device-secret":this.deviceSecret,"x-installation-id":this.config.installationId};}
  private async json(response:Response){const data=await response.json();if(!response.ok)throw new Error(data.error??`Cloud request failed (${response.status})`);return data;}
  async synchronize(){const started=Date.now(),operations=this.store.pendingEnvelopes();this.log("sync_start",{count:operations.length});try{if(operations.length){this.store.markAttempt(operations.map(op=>String(op.operationId)));try{const pushed=await this.json(await fetch(`${this.config.cloudUrl}/api/device/sync`,{method:"POST",headers:this.headers(),body:JSON.stringify({action:"push",operations})}));this.store.applyAcks(pushed.acknowledgements,pushed.serverTime);const conflicts=(pushed.acknowledgements as Array<{status?:string}>).filter(item=>item.status==="CONFLICTED"||item.status==="QUARANTINED").length;if(conflicts)this.log("sync_conflict",{count:conflicts});}catch(error){this.store.markAttempt(operations.map(op=>String(op.operationId)),error instanceof Error?error.message:"Network failure");this.log("sync_retry_scheduled",{count:operations.length,category:"push_failed"});throw error;}}const after=this.store.state().checkpoint;const pulled=await this.json(await fetch(`${this.config.cloudUrl}/api/device/sync?after=${after}`,{headers:this.headers()}));this.store.applyPull(pulled.events,pulled.checkpoint,pulled.serverTime);const state=this.store.state();this.log("sync_end",{durationMs:Date.now()-started,pending:state.pending,conflicted:state.conflicted,checkpoint:state.checkpoint,result:"success"});return state;}catch(error){const category=error instanceof Error&&/revok/i.test(error.message)?"device_revoked":"request_failed";this.log(category==="device_revoked"?"device_revoke_detected":"sync_failure",{durationMs:Date.now()-started,category,result:"failed"});throw error;}}
  async refreshUser(username:string,password:string){return this.json(await fetch(`${this.config.cloudUrl}/api/device/sync`,{method:"POST",headers:this.headers(),body:JSON.stringify({action:"refresh",username,password})}));}
  async collectDue(session:LocalSession,input:{billOperationId:string;operationId:string;amount:string;method:string;reference?:string}){return this.json(await fetch(`${this.config.cloudUrl}/api/device/online-action`,{method:"POST",headers:this.headers(),body:JSON.stringify({action:"collectDue",input:{...input,leaseToken:session.leaseToken}})}));}
}
