export const LAB_VERIFICATION_ERROR_CODES = {
  LAB_VERIFICATION_NOT_FOUND: "LAB_VERIFICATION_NOT_FOUND",
  LAB_VERIFICATION_ACCESS_DENIED: "LAB_VERIFICATION_ACCESS_DENIED",
  LAB_VERIFICATION_CROSS_TENANT: "LAB_VERIFICATION_CROSS_TENANT",
  LAB_VERIFICATION_INVALID_STATUS: "LAB_VERIFICATION_INVALID_STATUS",
  LAB_VERIFICATION_RESULT_NOT_READY: "LAB_VERIFICATION_RESULT_NOT_READY",
  LAB_VERIFICATION_ALREADY_VERIFIED: "LAB_VERIFICATION_ALREADY_VERIFIED",
  LAB_VERIFICATION_REJECTION_REASON_REQUIRED: "LAB_VERIFICATION_REJECTION_REASON_REQUIRED",
  LAB_VERIFICATION_SELF_APPROVAL_DENIED: "LAB_VERIFICATION_SELF_APPROVAL_DENIED",
  LAB_VERIFICATION_DEPARTMENT_ACCESS_DENIED: "LAB_VERIFICATION_DEPARTMENT_ACCESS_DENIED",
  LAB_VERIFICATION_BRANCH_ACCESS_DENIED: "LAB_VERIFICATION_BRANCH_ACCESS_DENIED",
  LAB_VERIFICATION_CRITICAL_UNACKNOWLEDGED: "LAB_VERIFICATION_CRITICAL_UNACKNOWLEDGED",
  LAB_VERIFICATION_REQUIRED_RESULT_MISSING: "LAB_VERIFICATION_REQUIRED_RESULT_MISSING",
  LAB_VERIFICATION_VERSION_CONFLICT: "LAB_VERIFICATION_VERSION_CONFLICT",
  LAB_CORRECTION_REQUEST_NOT_FOUND: "LAB_CORRECTION_REQUEST_NOT_FOUND",
  LAB_CORRECTION_ALREADY_RESOLVED: "LAB_CORRECTION_ALREADY_RESOLVED",
  LAB_CORRECTION_REASON_REQUIRED: "LAB_CORRECTION_REASON_REQUIRED",
  LAB_CORRECTION_INVALID_STATUS: "LAB_CORRECTION_INVALID_STATUS",
  LAB_RESULT_VERIFIED_LOCKED: "LAB_RESULT_VERIFIED_LOCKED",
  LAB_VERIFICATION_VALIDATION: "LAB_VERIFICATION_VALIDATION",
} as const;

export type LabVerificationErrorCode =
  (typeof LAB_VERIFICATION_ERROR_CODES)[keyof typeof LAB_VERIFICATION_ERROR_CODES];
